import type { Metadata } from "next";
import { Footer, Header, PageHero } from "../components/SiteChrome";
import { clubMedia } from "../lib/clubMedia";
import { getLiveSiteContent } from "../lib/liveSiteContent";
import { getPublicPageSettings,pageCopy } from "../lib/publicPageSettings";

export async function generateMetadata():Promise<Metadata>{const site=await getLiveSiteContent();const brand=site.settings.shortName||site.settings.clubName||"NYU Perú";return{title:`Culture | ${brand}`,description:"Explore Peruvian food, music, dance, heritage and cultural programming through the NYU Peruvian Student Association."};}
export const dynamic="force-dynamic";
export default async function CulturePage(){
  const site=await getLiveSiteContent();const brand=site.settings.shortName||site.settings.clubName||"NYU Perú";
  const page=await getPublicPageSettings("culture",{eyebrow:"Culture",title:"Peru in motion.",subtitle:"Food, music, heritage, art and traditions carried forward through student life at NYU."});
  const layoutClass=`page-layout-${page.layout.heroAlign} page-layout-${page.layout.contentWidth} page-spacing-${page.layout.sectionSpacing}`;
  return <main className={layoutClass}><Header/><PageHero eyebrow={page.eyebrow} title={page.title.replaceAll("{{brand}}",brand)} subtitle={page.subtitle.replaceAll("{{brand}}",brand)}/>
    <section className="page-section"><div className="wrap culture-feature-grid"><article><div className="culture-photo" style={clubMedia.engage.causa}/><span className="kicker">Gastronomía</span><h2>{pageCopy(page,"foodHeading","Causa Limeña")}</h2><p>{pageCopy(page,"foodBody","NYU Engage documents this traditional Peruvian dish of seasoned yellow potato purée layered with tuna salad and avocado, finished with a Peruvian olive garnish.")}</p><a className="text-link" href="https://engage.nyu.edu/organization/viva-peru-all-university/gallery" target="_blank" rel="noreferrer">Source: NYU Engage →</a></article><article><div className="culture-photo" style={clubMedia.engage.evaGroup}/><span className="kicker">Música</span><h2>{pageCopy(page,"musicHeading","A conversation with Eva Ayllón")}</h2><p>{pageCopy(page,"musicBody",`In October 2023, members of ${brand} met legendary Peruvian singer Eva Ayllón for a conversation about her life, career and música criolla.`).replaceAll("{{brand}}",brand)}</p><a className="text-link" href="https://engage.nyu.edu/organization/viva-peru-all-university/gallery" target="_blank" rel="noreferrer">Explore the archive →</a></article></div></section>
    <section className="page-section alt"><div className="wrap"><span className="kicker">Culture at NYU</span><h2 className="section-heading">{pageCopy(page,"traditionsHeading","Living traditions, not museum pieces.")}</h2><div className="info-grid"><article><h3>Music</h3><p>From música criolla to contemporary Peruvian voices, club events connect students with artists and living traditions.</p></article><article><h3>Food</h3><p>Shared meals turn regional dishes into an accessible entry point for stories, memory and community.</p></article><article><h3>Heritage</h3><p>Programs explore Peru&apos;s Andean, Indigenous, Afro-Peruvian, Asian-Peruvian and diasporic histories.</p></article><article><h3>Dance</h3><p>Performances such as Marinera Norteña bring movement, costume and regional identity into student programming.</p></article></div></div></section>
    <section className="page-section"><div className="wrap split-feature"><div><span className="kicker">Across New York</span><h2>{pageCopy(page,"cityHeading","Peruvian culture beyond campus.")}</h2><p>{pageCopy(page,"cityBody","In March 2025, Peruvian students from NYU, CUNY Hunter College and Columbia University visited The Metropolitan Museum of Art in collaboration with the Consulate General of Peru in New York.")}</p><a className="text-link" href="https://www.gob.pe/institucion/rree/noticias/1132670-universitarios-peruanos-visitaron-el-museo-metropolitano-de-arte-de-nueva-york" target="_blank" rel="noreferrer">Official source →</a></div><div className="photo-card tall" style={{backgroundImage:`url(${clubMedia.metVisit[0]})`,backgroundSize:"cover",backgroundPosition:"center"}}><span>{brand} at The Met · 2025</span></div></div></section>
    <Footer/></main>;
}
