"use client";

import { useEffect,useMemo,useState } from "react";

type Settings={clubName:string;shortName:string;email:string;instagram:string;linkedin:string;facebook:string;cmsConfig:Record<string,any>;updatedAt?:string};
type Section="General"|"Website"|"Team"|"Events"|"Media"|"Join"|"Social"|"Newsletter"|"SEO"|"Analytics"|"Publishing"|"Admin"|"System";
const sections:Section[]=["General","Website","Team","Events","Media","Join","Social","Newsletter","SEO","Analytics","Publishing","Admin","System"];
const defaults:Settings={clubName:"",shortName:"",email:"",instagram:"",linkedin:"",facebook:"",cmsConfig:{
 branding:{theme:"classic",primaryLogo:"/nyu-peruvian-logo-v4.svg",lightLogo:"/nyu-peruvian-logo-v4.svg",favicon:"",defaultHeroImage:"",defaultEventImage:"",defaultMemberImage:""},
 website:{maintenanceMode:false,maintenanceMessage:"We’ll be back shortly.",custom404:"We couldn’t find that page.",footerText:"",contactEmail:"",meetingLocation:"NYU · New York",defaultRsvpUrl:"",linkInBio:""},
 board:{currentYear:"2026–2027",showEmails:true,showBios:true,showLinkedIn:false,hideEmptyYears:true,autoArchiveOnAdvance:true,positionOrder:"President\nVice President\nTreasurer\nSecretary\nBoard Member"},
 announcement:{enabled:false,message:"",url:"",expiresAt:""},
 join:{applicationsOpen:true,ctaText:"Join NYU Perú",formUrl:"",deadline:"",meetingSchedule:"",dues:"",requirements:"",contactPerson:"",closedMessage:"Applications are currently closed."},
 social:{tiktok:"",youtube:"",groupChat:"",engage:"",linkInBio:""},
 homepage:{showEvents:true,showGallery:true,showNewsletter:true,showInstagram:true,showAbout:true,sectionOrder:["events","gallery","newsletter","instagram"]},
 events:{defaultLocation:"NYU · New York",defaultStatus:"draft",defaultCta:"RSVP",defaultRsvpUrl:"",autoArchivePast:true,hideRsvpAfterEvent:true,defaultCategory:"General",categories:"Social\nCultural\nProfessional\nCommunity Service\nGeneral Body Meeting",remindersEnabled:false},
 media:{defaultAlbum:"",showCaptions:true,showDates:true,allowVideo:true,homepageCount:6,approvalRequired:false,compression:"balanced"},
 newsletter:{senderName:"NYU Perú",replyTo:"",subjectPrefix:"",footerText:"",testRecipient:"",defaultHeader:"",signupConfirmation:"Thanks for subscribing!",unsubscribeConfirmation:"You have been unsubscribed."},
 seo:{titleSuffix:"NYU Peruvian Student Association",defaultDescription:"",defaultOgImage:"",indexingEnabled:true,canonicalDomain:"https://nyuperu.org",searchConsoleVerification:""},
 analytics:{gaId:"",trackRsvp:true,trackJoin:true,trackEmail:true,trackSocial:true,excludeAdminTraffic:true,defaultRange:"30d"},
 publishing:{confirmDeletes:true,warnUnsaved:true,previewBeforePublish:false,revisionHistory:true,trashEnabled:true,scheduledPublishing:false},
 admin:{density:"comfortable",rememberLastSection:true,defaultEventSort:"upcoming",collapsePastContent:true,quickActions:"event,media,member,newsletter"}
}};

const merge=(raw:Settings):Settings=>({...defaults,...raw,cmsConfig:{...defaults.cmsConfig,...raw.cmsConfig,...Object.fromEntries(Object.entries(defaults.cmsConfig).map(([k,v])=>[k,{...v,...(raw.cmsConfig?.[k]||{})}]))}});

export default function SettingsCenter({isSuperAdmin}:{isSuperAdmin:boolean}){
 const[data,setData]=useState<Settings>(defaults);const[section,setSection]=useState<Section>("General");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[dirty,setDirty]=useState(false);const[msg,setMsg]=useState("");const[system,setSystem]=useState<any>(null);
 useEffect(()=>{void(async()=>{const r=await fetch("/api/admin/settings",{cache:"no-store"});const d=await r.json();if(r.ok)setData(merge(d.settings));else setMsg(d.error||"Unable to load settings.");setLoading(false)})()},[]);
 useEffect(()=>{if(section!=="System"||system)return;void(async()=>{const r=await fetch("/api/admin/system",{cache:"no-store"});const d=await r.json();if(r.ok)setSystem(d)})()},[section,system]);
 useEffect(()=>{if(!dirty||data.cmsConfig.publishing?.warnUnsaved===false)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",fn);return()=>window.removeEventListener("beforeunload",fn)},[dirty,data.cmsConfig.publishing?.warnUnsaved]);
 const set=(key:keyof Settings,value:any)=>{setData(d=>({...d,[key]:value}));setDirty(true)};
 const patch=(group:string,key:string,value:any)=>{setData(d=>({...d,cmsConfig:{...d.cmsConfig,[group]:{...(d.cmsConfig[group]||{}),[key]:value}}}));setDirty(true)};
 async function save(){setSaving(true);setMsg("Saving…");const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();setSaving(false);if(r.ok){setDirty(false);setMsg("Settings saved and available to the site.")}else setMsg(d.error||"Save failed.")}
 const c=data.cmsConfig;
 const order=useMemo(()=>Array.isArray(c.homepage?.sectionOrder)?c.homepage.sectionOrder.join(", "):"events, gallery, newsletter, instagram",[c.homepage?.sectionOrder]);
 if(loading)return <main className="admin-loading">Loading Settings Center…</main>;
 const Toggle=({group,name,label,help}:{group:string;name:string;label:string;help?:string})=><label className="setting-toggle"><span><b>{label}</b>{help&&<small>{help}</small>}</span><input type="checkbox" checked={Boolean(c[group]?.[name])} onChange={e=>patch(group,name,e.target.checked)}/></label>;
 return <main className="settings-page"><aside className="settings-nav"><a className="settings-back" href="/admin">← Admin</a><div><span className="admin-kicker">Control center</span><h1>Settings</h1><p>Site-wide behavior and defaults.</p></div><nav>{sections.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav></aside><section className="settings-main"><header className="settings-head"><div><span className="admin-kicker">{section}</span><h2>{section} settings</h2></div><div className="settings-actions"><a href="/" target="_blank" rel="noreferrer">View site ↗</a><button className="admin-primary" disabled={!dirty||saving} onClick={save}>{saving?"Saving…":dirty?"Save changes":"Saved"}</button></div></header>{msg&&<div className="cms-notice">{msg}</div>}
 {section==="General"&&<div className="settings-grid"><article className="settings-card"><h3>Organization identity</h3><label>Formal organization name<input value={data.clubName} onChange={e=>set("clubName",e.target.value)}/></label><label>Public-facing name<input value={data.shortName} onChange={e=>set("shortName",e.target.value)}/></label><label>Contact email<input value={data.email} onChange={e=>set("email",e.target.value)}/></label></article><article className="settings-card"><h3>Brand assets</h3><label>Primary logo URL<input value={c.branding.primaryLogo||""} onChange={e=>patch("branding","primaryLogo",e.target.value)}/></label><label>Light logo URL<input value={c.branding.lightLogo||""} onChange={e=>patch("branding","lightLogo",e.target.value)}/></label><label>Favicon URL<input value={c.branding.favicon||""} onChange={e=>patch("branding","favicon",e.target.value)}/></label><label>Approved theme<select value={c.branding.theme||"classic"} onChange={e=>patch("branding","theme",e.target.value)}><option value="classic">Classic Peru Red</option><option value="light">Light</option><option value="dark">Dark</option></select></label></article><article className="settings-card"><h3>Default imagery</h3><label>Default hero image<input value={c.branding.defaultHeroImage||""} onChange={e=>patch("branding","defaultHeroImage",e.target.value)}/></label><label>Default event image<input value={c.branding.defaultEventImage||""} onChange={e=>patch("branding","defaultEventImage",e.target.value)}/></label><label>Default member image<input value={c.branding.defaultMemberImage||""} onChange={e=>patch("branding","defaultMemberImage",e.target.value)}/></label></article></div>}
 {section==="Website"&&<div className="settings-grid"><article className="settings-card"><h3>Announcement bar</h3><Toggle group="announcement" name="enabled" label="Show announcement bar"/><label>Message<input value={c.announcement.message||""} onChange={e=>patch("announcement","message",e.target.value)}/></label><label>Link<input value={c.announcement.url||""} onChange={e=>patch("announcement","url",e.target.value)}/></label><label>Expires<input type="datetime-local" value={c.announcement.expiresAt||""} onChange={e=>patch("announcement","expiresAt",e.target.value)}/></label></article><article className="settings-card"><h3>Homepage sections</h3><Toggle group="homepage" name="showAbout" label="About preview"/><Toggle group="homepage" name="showEvents" label="Events"/><Toggle group="homepage" name="showGallery" label="Gallery"/><Toggle group="homepage" name="showNewsletter" label="Newsletter"/><Toggle group="homepage" name="showInstagram" label="Instagram"/><label>Section order<small>Comma-separated</small><input value={order} onChange={e=>patch("homepage","sectionOrder",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/></label></article><article className="settings-card"><h3>Site behavior</h3><Toggle group="website" name="maintenanceMode" label="Maintenance mode" help="Use only when the public site should be temporarily unavailable."/><label>Maintenance message<textarea value={c.website.maintenanceMessage||""} onChange={e=>patch("website","maintenanceMessage",e.target.value)}/></label><label>Custom 404 message<textarea value={c.website.custom404||""} onChange={e=>patch("website","custom404",e.target.value)}/></label><label>Footer text<input value={c.website.footerText||""} onChange={e=>patch("website","footerText",e.target.value)}/></label><label>General meeting location<input value={c.website.meetingLocation||""} onChange={e=>patch("website","meetingLocation",e.target.value)}/></label><label>Default RSVP URL<input value={c.website.defaultRsvpUrl||""} onChange={e=>patch("website","defaultRsvpUrl",e.target.value)}/></label></article></div>}
 {section==="Team"&&<div className="settings-grid"><article className="settings-card"><h3>Board year</h3><label>Current academic year<input value={c.board.currentYear||""} onChange={e=>patch("board","currentYear",e.target.value)}/></label><p className="setting-help">The Team editor has an “Advance board year” action that archives current members and prepares the next year.</p><Toggle group="board" name="autoArchiveOnAdvance" label="Archive current board on rollover"/><Toggle group="board" name="hideEmptyYears" label="Hide empty archive years"/></article><article className="settings-card"><h3>Public member information</h3><Toggle group="board" name="showEmails" label="Show member emails"/><Toggle group="board" name="showBios" label="Show bios"/><Toggle group="board" name="showLinkedIn" label="Show LinkedIn buttons"/></article><article className="settings-card"><h3>Officer ordering</h3><label>Position order<small>One position per line</small><textarea rows={9} value={c.board.positionOrder||""} onChange={e=>patch("board","positionOrder",e.target.value)}/></label></article></div>}
 {section==="Events"&&<div className="settings-grid"><article className="settings-card"><h3>New event defaults</h3><label>Default location<input value={c.events.defaultLocation||""} onChange={e=>patch("events","defaultLocation",e.target.value)}/></label><label>Default status<select value={c.events.defaultStatus||"draft"} onChange={e=>patch("events","defaultStatus",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Default CTA<select value={c.events.defaultCta||"RSVP"} onChange={e=>patch("events","defaultCta",e.target.value)}><option>RSVP</option><option>Buy Tickets</option><option>Learn More</option><option>Join Waitlist</option></select></label><label>Default RSVP URL<input value={c.events.defaultRsvpUrl||""} onChange={e=>patch("events","defaultRsvpUrl",e.target.value)}/></label></article><article className="settings-card"><h3>Lifecycle</h3><Toggle group="events" name="autoArchivePast" label="Automatically archive past events"/><Toggle group="events" name="hideRsvpAfterEvent" label="Hide RSVP after event date"/><Toggle group="events" name="remindersEnabled" label="Event reminders enabled"/></article><article className="settings-card"><h3>Categories</h3><label>Default category<input value={c.events.defaultCategory||""} onChange={e=>patch("events","defaultCategory",e.target.value)}/></label><label>Available categories<small>One per line</small><textarea value={c.events.categories||""} onChange={e=>patch("events","categories",e.target.value)}/></label></article></div>}
 {section==="Media"&&<div className="settings-grid"><article className="settings-card"><h3>Library defaults</h3><label>Default album<input value={c.media.defaultAlbum||""} onChange={e=>patch("media","defaultAlbum",e.target.value)}/></label><label>Homepage media count<input type="number" min="1" max="24" value={c.media.homepageCount||6} onChange={e=>patch("media","homepageCount",Number(e.target.value)||6)}/></label><label>Image handling<select value={c.media.compression||"balanced"} onChange={e=>patch("media","compression",e.target.value)}><option value="quality">Maximum quality</option><option value="balanced">Balanced</option><option value="small">Smaller files</option></select></label></article><article className="settings-card"><h3>Display & approvals</h3><Toggle group="media" name="showCaptions" label="Show captions"/><Toggle group="media" name="showDates" label="Show dates"/><Toggle group="media" name="allowVideo" label="Allow video embeds"/><Toggle group="media" name="approvalRequired" label="Require media approval"/></article><article className="settings-card"><h3>Library tools</h3><a className="settings-link" href="/admin/drive">Import from Google Drive →</a><p className="setting-help">The Gallery editor includes search, albums, tags, event links, featured status and source URLs.</p></article></div>}
 {section==="Join"&&<div className="settings-grid"><article className="settings-card"><h3>Recruitment status</h3><Toggle group="join" name="applicationsOpen" label="Applications are open"/><label>Primary CTA<input value={c.join.ctaText||""} onChange={e=>patch("join","ctaText",e.target.value)}/></label><label>Membership/application URL<input value={c.join.formUrl||""} onChange={e=>patch("join","formUrl",e.target.value)}/></label><label>Deadline<input type="date" value={c.join.deadline||""} onChange={e=>patch("join","deadline",e.target.value)}/></label><label>Closed message<textarea value={c.join.closedMessage||""} onChange={e=>patch("join","closedMessage",e.target.value)}/></label></article><article className="settings-card"><h3>Membership information</h3><label>Meeting schedule<input value={c.join.meetingSchedule||""} onChange={e=>patch("join","meetingSchedule",e.target.value)}/></label><label>Dues<input value={c.join.dues||""} onChange={e=>patch("join","dues",e.target.value)}/></label><label>Contact person<input value={c.join.contactPerson||""} onChange={e=>patch("join","contactPerson",e.target.value)}/></label><label>Requirements<textarea value={c.join.requirements||""} onChange={e=>patch("join","requirements",e.target.value)}/></label></article></div>}
 {section==="Social"&&<div className="settings-grid"><article className="settings-card"><h3>Primary channels</h3><label>Instagram<input value={data.instagram} onChange={e=>set("instagram",e.target.value)}/></label><label>Facebook<input value={data.facebook} onChange={e=>set("facebook",e.target.value)}/></label><label>LinkedIn<input value={data.linkedin} onChange={e=>set("linkedin",e.target.value)}/></label></article><article className="settings-card"><h3>Additional channels</h3><label>TikTok<input value={c.social.tiktok||""} onChange={e=>patch("social","tiktok",e.target.value)}/></label><label>YouTube<input value={c.social.youtube||""} onChange={e=>patch("social","youtube",e.target.value)}/></label><label>Group chat / GroupMe / Discord<input value={c.social.groupChat||""} onChange={e=>patch("social","groupChat",e.target.value)}/></label><label>NYU Engage<input value={c.social.engage||""} onChange={e=>patch("social","engage",e.target.value)}/></label><label>Link in bio<input value={c.social.linkInBio||""} onChange={e=>patch("social","linkInBio",e.target.value)}/></label></article><article className="settings-card"><h3>Social managers</h3><a className="settings-link" href="/admin/instagram">Instagram manager →</a>{isSuperAdmin&&<a className="settings-link" href="/admin/facebook">Facebook manager →</a>}</article></div>}
 {section==="Newsletter"&&<div className="settings-grid"><article className="settings-card"><h3>Sender defaults</h3><label>Sender name<input value={c.newsletter.senderName||""} onChange={e=>patch("newsletter","senderName",e.target.value)}/></label><label>Reply-to email<input value={c.newsletter.replyTo||""} onChange={e=>patch("newsletter","replyTo",e.target.value)}/></label><label>Subject prefix<input value={c.newsletter.subjectPrefix||""} onChange={e=>patch("newsletter","subjectPrefix",e.target.value)}/></label><label>Test recipient<input value={c.newsletter.testRecipient||""} onChange={e=>patch("newsletter","testRecipient",e.target.value)}/></label></article><article className="settings-card"><h3>Reusable content</h3><label>Default header<textarea value={c.newsletter.defaultHeader||""} onChange={e=>patch("newsletter","defaultHeader",e.target.value)}/></label><label>Email footer<textarea value={c.newsletter.footerText||""} onChange={e=>patch("newsletter","footerText",e.target.value)}/></label><label>Signup confirmation<input value={c.newsletter.signupConfirmation||""} onChange={e=>patch("newsletter","signupConfirmation",e.target.value)}/></label><label>Unsubscribe confirmation<input value={c.newsletter.unsubscribeConfirmation||""} onChange={e=>patch("newsletter","unsubscribeConfirmation",e.target.value)}/></label></article><article className="settings-card"><h3>Newsletter workspace</h3><a className="settings-link" href="/admin/newsletter">Open newsletter manager →</a></article></div>}
 {section==="SEO"&&<div className="settings-grid"><article className="settings-card"><h3>Metadata defaults</h3><label>Title suffix<input value={c.seo.titleSuffix||""} onChange={e=>patch("seo","titleSuffix",e.target.value)}/></label><label>Default meta description<textarea value={c.seo.defaultDescription||""} onChange={e=>patch("seo","defaultDescription",e.target.value)}/></label><label>Default social image<input value={c.seo.defaultOgImage||""} onChange={e=>patch("seo","defaultOgImage",e.target.value)}/></label></article><article className="settings-card"><h3>Indexing</h3><Toggle group="seo" name="indexingEnabled" label="Allow search engine indexing"/><label>Canonical domain<input value={c.seo.canonicalDomain||""} onChange={e=>patch("seo","canonicalDomain",e.target.value)}/></label><label>Search Console verification<input value={c.seo.searchConsoleVerification||""} onChange={e=>patch("seo","searchConsoleVerification",e.target.value)}/></label></article></div>}
 {section==="Analytics"&&<div className="settings-grid"><article className="settings-card"><h3>Analytics provider</h3><label>Google Analytics ID<input placeholder="G-XXXXXXXXXX" value={c.analytics.gaId||""} onChange={e=>patch("analytics","gaId",e.target.value)}/></label><label>Default dashboard range<select value={c.analytics.defaultRange||"30d"} onChange={e=>patch("analytics","defaultRange",e.target.value)}><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select></label></article><article className="settings-card"><h3>Conversion tracking</h3><Toggle group="analytics" name="trackRsvp" label="Track RSVP clicks"/><Toggle group="analytics" name="trackJoin" label="Track Join clicks"/><Toggle group="analytics" name="trackEmail" label="Track email clicks"/><Toggle group="analytics" name="trackSocial" label="Track social links"/><Toggle group="analytics" name="excludeAdminTraffic" label="Exclude admin traffic"/></article><article className="settings-card"><a className="settings-link" href="/admin/analytics">Open analytics dashboard →</a></article></div>}
 {section==="Publishing"&&<div className="settings-grid"><article className="settings-card"><h3>Safety</h3><Toggle group="publishing" name="confirmDeletes" label="Confirm destructive actions"/><Toggle group="publishing" name="warnUnsaved" label="Warn before leaving with unsaved changes"/><Toggle group="publishing" name="previewBeforePublish" label="Preview before publishing"/></article><article className="settings-card"><h3>Recovery & workflow</h3><Toggle group="publishing" name="trashEnabled" label="Trash / restore enabled"/><Toggle group="publishing" name="revisionHistory" label="Revision history enabled"/><Toggle group="publishing" name="scheduledPublishing" label="Scheduled publishing"/><p className="setting-help">Trash and revision storage are maintained by the CMS backend; this page controls whether editors use those protections.</p></article></div>}
 {section==="Admin"&&<div className="settings-grid"><article className="settings-card"><h3>Editor preferences</h3><label>Editor density<select value={c.admin.density||"comfortable"} onChange={e=>patch("admin","density",e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><Toggle group="admin" name="rememberLastSection" label="Remember last-opened Admin section"/><Toggle group="admin" name="collapsePastContent" label="Collapse past/archived content"/><label>Default event sort<select value={c.admin.defaultEventSort||"upcoming"} onChange={e=>patch("admin","defaultEventSort",e.target.value)}><option value="upcoming">Upcoming first</option><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label><label>Dashboard quick actions<small>Comma-separated keys</small><input value={c.admin.quickActions||""} onChange={e=>patch("admin","quickActions",e.target.value)}/></label></article><article className="settings-card"><h3>Access</h3><a className="settings-link" href="/admin/users">Users & Access →</a><p className="setting-help">Role-based permissions remain centralized in Users & Access so individual editors cannot accidentally grant themselves privileges.</p></article></div>}
 {section==="System"&&<div className="settings-grid system-grid"><article className="settings-card"><h3>Site health</h3>{!system?<p>Checking system status…</p>:<><div className="health-row"><span>Database</span><b className={system.health.database==="healthy"?"ok":"bad"}>{system.health.database}</b></div><div className="health-row"><span>Authentication</span><b className="ok">{system.health.auth}</b></div><div className="health-row"><span>Environment</span><b>{system.health.environment}</b></div><div className="health-row"><span>Production commit</span><code>{String(system.health.productionCommit).slice(0,12)}</code></div><div className="health-row"><span>Events / Team / Media</span><b>{system.health.counts.events} / {system.health.counts.team} / {system.health.counts.media}</b></div></>}</article><article className="settings-card activity-card"><h3>Recent admin activity</h3>{system?.activity?.length?system.activity.map((x:any)=><div className="activity-row" key={x.id}><b>{String(x.action).replaceAll("_"," ")}</b><span>{x.entity_type}</span><time>{new Date(x.created_at).toLocaleString()}</time></div>):<p>No recent activity available.</p>}</article></div>}
 </section></main>;
}
