import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "../../lib/supabase/server";

export const dynamic="force-dynamic";
const pct=(v:number,t:number)=>t?`${Math.round(v/t*100)}%`:"0%";
const dayKey=(v:string|Date)=>new Date(v).toISOString().slice(0,10);

export default async function AnalyticsPage(){
 const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/admin/login");const{data:profile}=await supabase.from("profiles").select("role,status").eq("id",user.id).single();if(!profile||profile.status!=="active"||!["super_admin","admin"].includes(profile.role))redirect("/admin");
 const since=new Date(Date.now()-30*86400000).toISOString();const[eventsR,subsR,deliveriesR,campaignsR]=await Promise.all([supabase.from("site_events").select("event_type,path,session_id,metadata,created_at").gte("created_at",since).order("created_at",{ascending:false}).limit(10000),supabase.from("newsletter_subscribers").select("status,created_at,unsubscribed_at"),supabase.from("newsletter_deliveries").select("campaign_id,status,opened_at,clicked_at,open_count,click_count,sent_at,scheduled_for"),supabase.from("newsletter_campaigns").select("id,subject,status,sent_at,scheduled_for,created_at").order("created_at",{ascending:false}).limit(20)]);
 const events=eventsR.data||[],subs=subsR.data||[],deliveries=deliveriesR.data||[],campaigns=campaignsR.data||[];const views=events.filter(e=>e.event_type==="page_view"),clicks=events.filter(e=>e.event_type==="cta_click"),sessions=new Set(views.map(e=>e.session_id).filter(Boolean)).size,activeSubs=subs.filter(s=>s.status==="subscribed").length,sent=deliveries.filter(d=>d.status==="sent"||d.status==="scheduled").length,opened=deliveries.filter(d=>d.opened_at).length,clicked=deliveries.filter(d=>d.clicked_at).length;
 const pageCounts=new Map<string,number>();views.forEach(v=>pageCounts.set(v.path,(pageCounts.get(v.path)||0)+1));const topPages=[...pageCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8);const ctaCounts=new Map<string,number>();clicks.forEach(c=>{const label=String((c.metadata as Record<string,unknown>|null)?.label||"CTA");ctaCounts.set(label,(ctaCounts.get(label)||0)+1)});const topCtas=[...ctaCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8);
 const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(13-i));return d});const traffic=days.map(d=>({day:d,label:d.toLocaleDateString("en-US",{month:"short",day:"numeric"}),views:views.filter(v=>dayKey(v.created_at)===dayKey(d)).length,sessions:new Set(views.filter(v=>dayKey(v.created_at)===dayKey(d)).map(v=>v.session_id).filter(Boolean)).size}));const maxViews=Math.max(1,...traffic.map(d=>d.views));
 const growth=days.map(d=>({label:d.toLocaleDateString("en-US",{month:"short",day:"numeric"}),count:subs.filter(s=>new Date(s.created_at)<=new Date(`${dayKey(d)}T23:59:59`)&&(!s.unsubscribed_at||new Date(s.unsubscribed_at)>new Date(`${dayKey(d)}T23:59:59`))).length}));const maxGrowth=Math.max(1,...growth.map(d=>d.count));
 const campaignMetrics=campaigns.map(c=>{const ds=deliveries.filter(d=>d.campaign_id===c.id),delivered=ds.filter(d=>d.status==="sent"||d.status==="scheduled").length,o=ds.filter(d=>d.opened_at).length,k=ds.filter(d=>d.clicked_at).length;return{...c,delivered,o,k}});
 const card:React.CSSProperties={background:"white",border:"1px solid #ddd5cb",borderRadius:18,padding:22};
 return <main style={{minHeight:"100vh",background:"#f4ede4",padding:"28px 16px 70px",fontFamily:"var(--font-sans)"}}><div style={{maxWidth:1180,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap",marginBottom:24}}><div><span className="admin-kicker">Admin analytics</span><h1 style={{fontFamily:"var(--font-display)",fontSize:"clamp(2.6rem,7vw,4.8rem)",margin:"4px 0"}}>Performance</h1><p style={{margin:0,opacity:.68}}>Website activity for the last 30 days plus newsletter and subscriber performance.</p></div><a href="/admin" className="admin-primary" style={{textDecoration:"none"}}>← Board CMS</a></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginBottom:18}}><article style={card}><b style={{fontSize:38}}>{views.length}</b><div>Page views · 30d</div></article><article style={card}><b style={{fontSize:38}}>{sessions}</b><div>Sessions · 30d</div></article><article style={card}><b style={{fontSize:38}}>{clicks.length}</b><div>CTA interactions</div></article><article style={card}><b style={{fontSize:38}}>{activeSubs}</b><div>Active subscribers</div></article><article style={card}><b style={{fontSize:38}}>{pct(opened,sent)}</b><div>Email open rate</div></article><article style={card}><b style={{fontSize:38}}>{pct(clicked,sent)}</b><div>Email click rate</div></article></section>
 <section style={{...card,marginBottom:16}}><span className="admin-kicker">Traffic trend</span><h2 style={{fontFamily:"var(--font-display)",fontSize:30}}>Last 14 days</h2><div style={{display:"grid",gridTemplateColumns:`repeat(${traffic.length},minmax(24px,1fr))`,gap:6,alignItems:"end",height:220,overflowX:"auto"}}>{traffic.map(d=><div key={d.label} title={`${d.label}: ${d.views} views`} style={{display:"grid",gridTemplateRows:"1fr auto",height:"100%",alignItems:"end",gap:6}}><div style={{height:`${Math.max(4,d.views/maxViews*170)}px`,background:"#c91525",borderRadius:"7px 7px 2px 2px"}}/><small style={{fontSize:10,textAlign:"center",writingMode:"vertical-rl",transform:"rotate(180deg)",height:38}}>{d.label}</small></div>)}</div></section>
 <section style={{...card,marginBottom:16}}><span className="admin-kicker">Subscriber growth</span><h2 style={{fontFamily:"var(--font-display)",fontSize:30}}>Active audience · 14 days</h2><div style={{display:"grid",gridTemplateColumns:`repeat(${growth.length},minmax(24px,1fr))`,gap:6,alignItems:"end",height:180,overflowX:"auto"}}>{growth.map(d=><div key={d.label} title={`${d.label}: ${d.count} active subscribers`} style={{display:"grid",gridTemplateRows:"1fr auto",height:"100%",alignItems:"end",gap:6}}><div style={{height:`${Math.max(4,d.count/maxGrowth*130)}px`,background:"#171412",borderRadius:"7px 7px 2px 2px"}}/><small style={{fontSize:10,textAlign:"center"}}>{d.count}</small></div>)}</div></section>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16,marginBottom:16}}><section style={card}><span className="admin-kicker">Website</span><h2 style={{fontFamily:"var(--font-display)",fontSize:30}}>Top pages</h2>{topPages.length?topPages.map(([path,count])=><div key={path} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #eee"}}><span>{path}</span><b>{count}</b></div>):<p>No page-view data yet.</p>}</section><section style={card}><span className="admin-kicker">Interactions</span><h2 style={{fontFamily:"var(--font-display)",fontSize:30}}>Top calls to action</h2>{topCtas.length?topCtas.map(([label,count])=><div key={label} style={{display:"flex",justifyContent:"space-between",gap:12,padding:"10px 0",borderBottom:"1px solid #eee"}}><span>{label}</span><b>{count}</b></div>):<p>No CTA-click data yet.</p>}</section></div>
 <section style={card}><span className="admin-kicker">Campaign performance</span><h2 style={{fontFamily:"var(--font-display)",fontSize:30}}>Recent newsletters</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:680}}><thead><tr><th align="left">Campaign</th><th>Status</th><th>Recipients</th><th>Open rate</th><th>Click rate</th></tr></thead><tbody>{campaignMetrics.map(c=><tr key={c.id} style={{borderTop:"1px solid #eee"}}><td style={{padding:"12px 6px"}}><b>{c.subject}</b><small style={{display:"block",opacity:.6}}>{c.scheduled_for?`Scheduled ${new Date(c.scheduled_for).toLocaleString()}`:c.sent_at?new Date(c.sent_at).toLocaleDateString():new Date(c.created_at).toLocaleDateString()}</small></td><td align="center">{c.status}</td><td align="center">{c.delivered}</td><td align="center">{pct(c.o,c.delivered)}</td><td align="center">{pct(c.k,c.delivered)}</td></tr>)}</tbody></table>{!campaignMetrics.length&&<p>No campaigns yet.</p>}</div></section>
 </div></main>;
}
