import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "../../../lib/supabase/server";

const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
type EventItem={id:string;title:string;slug?:string;date:string;time:string;endTime?:string;location:string;description:string;details?:string;image:string;rsvpUrl:string;status:string;schedule?:{time:string;label:string}[];faq?:{question:string;answer:string}[]};
type TeamItem={id:string;name:string;role:string;email:string;image:string;bio?:string;boardYear?:string;active?:boolean};
type GalleryItem={id:string;title:string;image:string;description:string;sourceUrl?:string;mediaType?:"image"|"video";createdAt?:string;year?:number;album?:string;tags?:string[];featured?:boolean;eventId?:string};
type CmsConfig=Record<string,unknown>;
type SiteContent={homepage:{headline:string;description:string;heroImage:string;featuredEventId:string;videoUrl?:string;videoPosterUrl?:string;secondaryVideoUrl?:string;secondaryVideoPosterUrl?:string};events:EventItem[];team:TeamItem[];gallery:GalleryItem[];settings:{clubName:string;shortName:string;email:string;instagram:string;linkedin:string;facebook:string;cmsConfig:CmsConfig}};
type SupabaseClient=Awaited<ReturnType<typeof createSupabaseServerClient>>;

async function adminContext(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{supabase,user:null,profile:null};const {data:profile}=await supabase.from("profiles").select("email,role,status").eq("id",user.id).single();return{supabase,user,profile};}

async function loadContent(supabase:SupabaseClient):Promise<SiteContent>{
  const [homeResult,eventResult,teamResult,galleryResult,settingsResult]=await Promise.all([
    supabase.from("homepage_content").select("headline,description,hero_image,featured_event_id,video_url,video_poster_url,secondary_video_url,secondary_video_poster_url").eq("id",1).single(),
    supabase.from("events").select("id,title,slug,event_date,start_time,end_time,location,description,details,image_url,rsvp_url,status,schedule,faq").order("event_date",{ascending:false,nullsFirst:false}),
    supabase.from("team_members").select("id,name,title,bio,email,image_url,board_year,sort_order,active").order("active",{ascending:false}).order("board_year",{ascending:false,nullsFirst:false}).order("sort_order",{ascending:true}),
    supabase.from("gallery_items").select("id,title,image_url,caption,source_url,media_type,sort_order,created_at,year,album,tags,featured,event_id").order("featured",{ascending:false}).order("sort_order",{ascending:true}),
    supabase.from("site_settings").select("club_name,short_name,email,instagram,linkedin,facebook,cms_config").eq("id",1).single(),
  ]);
  const firstError=homeResult.error||eventResult.error||teamResult.error||galleryResult.error||settingsResult.error;if(firstError)throw firstError;
  const home=homeResult.data!;const settings=settingsResult.data!;
  return{homepage:{headline:home.headline,description:home.description,heroImage:home.hero_image,featuredEventId:home.featured_event_id||"",videoUrl:home.video_url||"",videoPosterUrl:home.video_poster_url||"",secondaryVideoUrl:home.secondary_video_url||"",secondaryVideoPosterUrl:home.secondary_video_poster_url||""},events:(eventResult.data||[]).map(item=>({id:item.id,title:item.title,slug:item.slug||"",date:item.event_date||"",time:item.start_time?String(item.start_time).slice(0,5):"",endTime:item.end_time?String(item.end_time).slice(0,5):"",location:item.location,description:item.description,details:item.details||"",image:item.image_url,rsvpUrl:item.rsvp_url,status:item.status,schedule:Array.isArray(item.schedule)?item.schedule:[],faq:Array.isArray(item.faq)?item.faq:[]})),team:(teamResult.data||[]).map(item=>({id:item.id,name:item.name,role:item.title,email:item.email,image:item.image_url,bio:item.bio||"",boardYear:item.board_year||"",active:item.active})),gallery:(galleryResult.data||[]).map(item=>({id:item.id,title:item.title,image:item.image_url,description:item.caption,sourceUrl:item.source_url,mediaType:(item.media_type||"image") as "image"|"video",createdAt:item.created_at,year:item.year||undefined,album:item.album||"",tags:item.tags||[],featured:Boolean(item.featured),eventId:item.event_id||""})),settings:{clubName:settings.club_name,shortName:settings.short_name,email:settings.email,instagram:settings.instagram,linkedin:settings.linkedin,facebook:settings.facebook||"",cmsConfig:(settings.cms_config&&typeof settings.cms_config==="object"?settings.cms_config:{}) as CmsConfig}};
}

export async function GET(){const{supabase,user,profile}=await adminContext();if(!user||!profile||profile.status!=="active")return NextResponse.json({error:"Unauthorized"},{status:401});try{return NextResponse.json({content:await loadContent(supabase),admin:profile.email,role:profile.role});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to load CMS content"},{status:500});}}

async function trashRow(supabase:SupabaseClient,entityType:string,row:Record<string,unknown>,userId:string,enabled:boolean){if(!enabled)return;const{error}=await supabase.from("cms_trash").insert({entity_type:entityType,entity_id:String(row.id||""),snapshot:row,deleted_by:userId});if(error)throw error;}
async function reconcileEvents(supabase:SupabaseClient,items:EventItem[],userId:string,trashEnabled:boolean){const{data:existing}=await supabase.from("events").select("*");const keep=new Set<string>();const idMap=new Map<string,string>();for(const item of items){const payload={title:item.title||"Untitled event",slug:slugify(item.slug||item.title)||null,event_date:item.date||null,start_time:item.time||null,end_time:item.endTime||null,location:item.location||"NYU · New York",description:item.description||"",details:item.details||"",image_url:item.image||"",rsvp_url:item.rsvpUrl||"",status:["draft","published","past"].includes(item.status)?item.status:"draft",schedule:Array.isArray(item.schedule)?item.schedule:[],faq:Array.isArray(item.faq)?item.faq:[],updated_by:userId};if(uuidPattern.test(item.id)){const{error}=await supabase.from("events").update(payload).eq("id",item.id);if(error)throw error;keep.add(item.id);idMap.set(item.id,item.id);}else{const{data,error}=await supabase.from("events").insert({...payload,created_by:userId}).select("id").single();if(error)throw error;keep.add(data.id);idMap.set(item.id,data.id);}}for(const row of existing||[])if(!keep.has(row.id)){await trashRow(supabase,"event",row,userId,trashEnabled);const{error}=await supabase.from("events").delete().eq("id",row.id);if(error)throw error;}return idMap;}
async function reconcileTeam(supabase:SupabaseClient,items:TeamItem[],userId:string,trashEnabled:boolean){const{data:existing}=await supabase.from("team_members").select("*");const keep=new Set<string>();for(const[index,item]of items.entries()){const payload={name:item.name||"Board Member",title:item.role||"Board Member",bio:item.bio||"",email:item.email||"",image_url:item.image||"",board_year:item.boardYear||"",sort_order:index,active:item.active!==false};if(uuidPattern.test(item.id)){const{error}=await supabase.from("team_members").update(payload).eq("id",item.id);if(error)throw error;keep.add(item.id);}else{const{data,error}=await supabase.from("team_members").insert(payload).select("id").single();if(error)throw error;keep.add(data.id);}}for(const row of existing||[])if(!keep.has(row.id)){await trashRow(supabase,"team_member",row,userId,trashEnabled);const{error}=await supabase.from("team_members").delete().eq("id",row.id);if(error)throw error;}}
async function reconcileGallery(supabase:SupabaseClient,items:GalleryItem[],userId:string,eventIdMap:Map<string,string>,trashEnabled:boolean){const{data:existing}=await supabase.from("gallery_items").select("*");const keep=new Set<string>();for(const[index,item]of items.entries()){if(!item.image)continue;const eventId=item.eventId?(eventIdMap.get(item.eventId)||(uuidPattern.test(item.eventId)?item.eventId:null)):null;const payload={title:item.title||"Gallery media",image_url:item.image,caption:item.description||"",source_url:item.sourceUrl||"",media_type:item.mediaType==="video"?"video":"image",year:item.year||null,album:item.album||"",tags:item.tags||[],featured:Boolean(item.featured),event_id:eventId,sort_order:index,published:true};if(uuidPattern.test(item.id)){const{error}=await supabase.from("gallery_items").update(payload).eq("id",item.id);if(error)throw error;keep.add(item.id);}else{const{data,error}=await supabase.from("gallery_items").insert({...payload,created_by:userId}).select("id").single();if(error)throw error;keep.add(data.id);}}for(const row of existing||[])if(!keep.has(row.id)){await trashRow(supabase,"gallery_item",row,userId,trashEnabled);const{error}=await supabase.from("gallery_items").delete().eq("id",row.id);if(error)throw error;}}

export async function PUT(request:Request){const{supabase,user,profile}=await adminContext();if(!user||!profile||profile.status!=="active")return NextResponse.json({error:"Unauthorized"},{status:401});const content=await request.json() as SiteContent;try{const role=profile.role;const publishing=((content.settings.cmsConfig as any)?.publishing||{}) as {trashEnabled?:boolean;revisionHistory?:boolean};const trashEnabled=publishing.trashEnabled!==false;const revisionEnabled=publishing.revisionHistory!==false;if(revisionEnabled){const previous=await loadContent(supabase);const{error:revisionError}=await supabase.from("cms_revisions").insert({entity_type:"site_content",entity_id:"1",snapshot:previous,created_by:user.id});if(revisionError)throw revisionError;}
 let eventIdMap=new Map<string,string>();if(["super_admin","admin","events_manager"].includes(role))eventIdMap=await reconcileEvents(supabase,content.events,user.id,trashEnabled);if(["super_admin","admin","team_manager"].includes(role))await reconcileTeam(supabase,content.team,user.id,trashEnabled);if(["super_admin","admin","media_manager"].includes(role))await reconcileGallery(supabase,content.gallery,user.id,eventIdMap,trashEnabled);if(["super_admin","admin"].includes(role)){const featured=content.homepage.featuredEventId?(eventIdMap.get(content.homepage.featuredEventId)||(uuidPattern.test(content.homepage.featuredEventId)?content.homepage.featuredEventId:null)):null;const{error:homeError}=await supabase.from("homepage_content").update({headline:content.homepage.headline,description:content.homepage.description,hero_image:content.homepage.heroImage,featured_event_id:featured,video_url:content.homepage.videoUrl||"",video_poster_url:content.homepage.videoPosterUrl||"",secondary_video_url:content.homepage.secondaryVideoUrl||"",secondary_video_poster_url:content.homepage.secondaryVideoPosterUrl||"",updated_by:user.id}).eq("id",1);if(homeError)throw homeError;const{error:settingsError}=await supabase.from("site_settings").update({club_name:content.settings.clubName,short_name:content.settings.shortName,email:content.settings.email,instagram:content.settings.instagram,linkedin:content.settings.linkedin,facebook:content.settings.facebook||"",cms_config:content.settings.cmsConfig||{},updated_by:user.id}).eq("id",1);if(settingsError)throw settingsError;}await supabase.from("audit_log").insert({actor_id:user.id,action:"cms_save",entity_type:"site_content",metadata:{role,revisionEnabled,trashEnabled}});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to save CMS content"},{status:500});}}
