"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";

const SITE_ORIGIN="https://nyuperu.org";
type ActivationState="checking"|"ready"|"recovery"|"success";
type SetupField={id:string;field_key:string;label:string;field_type:"text"|"textarea"|"select"|"number";placeholder:string;options:string[];required:boolean;team_column:string|null;sort_order:number;active:boolean};
const academicYear=(start:number)=>`${start}–${start+1}`;
const currentAcademicStart=()=>{const d=new Date();const y=d.getFullYear();return d.getMonth()>=6?y:y-1};

export default function AdminActivatePage(){
 const[state,setState]=useState<ActivationState>("checking"),[accountEmail,setAccountEmail]=useState(""),[fields,setFields]=useState<SetupField[]>([]),[values,setValues]=useState<Record<string,string>>({}),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[profileOnly,setProfileOnly]=useState(false),[recoveryEmail,setRecoveryEmail]=useState(""),[message,setMessage]=useState("Checking your secure invitation…"),[loading,setLoading]=useState(false);
 const boardYears=useMemo(()=>Array.from({length:Math.max(1,currentAcademicStart()-2016+1)},(_,i)=>academicYear(currentAcademicStart()-i)),[]);
 useEffect(()=>{const supabase=createSupabaseBrowserClient();void(async()=>{try{const search=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.replace(/^#/,"")),code=search.get("code"),tokenHash=search.get("token_hash"),queryType=search.get("type"),hashType=hash.get("type"),accessToken=hash.get("access_token"),refreshToken=hash.get("refresh_token"),completingProfile=search.get("flow")==="profile";setProfileOnly(completingProfile);if(code){const{error}=await supabase.auth.exchangeCodeForSession(code);if(error)throw error}else if(tokenHash&&["invite","magiclink","email","signup"].includes(queryType||"")){const{error}=await supabase.auth.verifyOtp({token_hash:tokenHash,type:queryType as "invite"|"magiclink"|"email"|"signup"});if(error)throw error}else if(accessToken&&refreshToken&&(hashType==="invite"||!hashType)){const{error}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)throw error}const{data:{session},error}=await supabase.auth.getSession();if(error)throw error;if(!session){setState("recovery");setMessage("This invitation is expired, already used, or did not retain its secure session. Request a fresh setup link below.");return}const email=session.user.email||"";setAccountEmail(email);setRecoveryEmail(email);const[{data:profile},{data:form,error:formError}]=await Promise.all([supabase.from("profiles").select("display_name,setup_data,status").eq("id",session.user.id).maybeSingle(),supabase.from("activation_setup_fields").select("*").eq("active",true).order("sort_order")]);if(formError)throw formError;const fs=(form||[]).map((x:any)=>({...x,options:Array.isArray(x.options)?x.options:[]})) as SetupField[];setFields(fs);const saved=(profile?.setup_data&&typeof profile.setup_data==="object"?profile.setup_data:{}) as Record<string,string>;const initial={...saved};for(const f of fs){if(f.team_column==="name"&&!initial[f.field_key])initial[f.field_key]=profile?.display_name||String(session.user.user_metadata?.display_name||"");if(f.team_column==="board_year"&&!initial[f.field_key])initial[f.field_key]=academicYear(currentAcademicStart())}setValues(initial);history.replaceState({},document.title,completingProfile?"/admin/activate?flow=profile":"/admin/activate");setState("ready");setMessage(completingProfile?"Finish your account setup to continue.":"Invitation verified. Finish your account setup below.")}catch(error){console.error("Activation error",error);setState("recovery");setMessage("This invitation is expired or has already been used. Request a fresh setup link below.")}})()},[]);
 async function sendRecovery(e:FormEvent){e.preventDefault();const email=recoveryEmail.trim();if(!email)return setMessage("Enter the email address that received the board invitation.");setLoading(true);const supabase=createSupabaseBrowserClient();const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${SITE_ORIGIN}/admin/reset-password`});setLoading(false);if(error)return setMessage(/rate/i.test(error.message)?"Too many setup emails were requested recently. Wait about a minute, then try again.":error.message);setMessage("Setup email sent. Open the newest email to continue.")}
 async function submit(e:FormEvent){e.preventDefault();for(const f of fields)if(f.required&&!String(values[f.field_key]||"").trim())return setMessage(`${f.label} is required.`);if(!profileOnly&&password.length<8)return setMessage("Use a password with at least 8 characters.");if(!profileOnly&&password!==confirm)return setMessage("The passwords do not match.");setLoading(true);const supabase=createSupabaseBrowserClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user){setLoading(false);setState("recovery");return setMessage("Your secure invitation session expired. Request a fresh setup link below.")}if(!profileOnly){const{error}=await supabase.auth.updateUser({password});if(error&&String((error as any).code||"")!=="same_password"&&!/different from the old password/i.test(error.message)){setLoading(false);return setMessage(error.message)}}const{error:finishError}=await supabase.rpc("finish_own_board_setup",{setup:values});if(finishError){setLoading(false);return setMessage(finishError.message)}const{data:refreshed,error:refreshError}=await supabase.auth.refreshSession();if(refreshError||!refreshed.session){setLoading(false);return setMessage("Your account was completed, but the session could not be refreshed. Sign in with your new password.")}setState("success");setMessage("Account setup complete. Opening your board portal…");location.replace("/admin")}
 const inputFor=(f:SetupField)=>{const value=values[f.field_key]||"",set=(v:string)=>setValues(x=>({...x,[f.field_key]:v})),opts=f.team_column==="board_year"&&!(f.options||[]).length?boardYears:(f.options||[]);if(f.field_type==="textarea")return <textarea rows={3} value={value} placeholder={f.placeholder} onChange={e=>set(e.target.value)} required={f.required}/>;if(f.field_type==="select")return <select value={value} onChange={e=>set(e.target.value)} required={f.required}><option value="">Select…</option>{opts.map(x=><option key={x} value={x}>{x}</option>)}</select>;return <input type={f.field_type==="number"?"number":"text"} value={value} placeholder={f.placeholder} onChange={e=>set(e.target.value)} required={f.required}/>};
 return <main className="admin-login-page"><section className="admin-login-card"><img src="/nyu-peruvian-logo-v4.svg" alt="NYU Peruvian Student Association logo" className="admin-login-logo"/><span className="admin-kicker">Board account</span><h1>{state==="success"?"Account setup complete":"Activate / finish account setup"}</h1><p>{message}</p>{state==="checking"&&<div className="cms-notice">Verifying invitation…</div>}{state==="ready"&&<>{accountEmail&&<div className="cms-notice"><b>Account</b><br/>{accountEmail}</div>}<form onSubmit={submit} className="admin-login-form">{fields.map(f=><label key={f.id}>{f.label}{!f.required&&<small> optional</small>}{inputFor(f)}</label>)}{!profileOnly&&<><label>New password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label><label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label></>}<button className="admin-primary" disabled={loading}>{loading?"Finishing…":profileOnly?"Finish account setup":"Activate account"}</button></form></>}{state==="recovery"&&<form onSubmit={sendRecovery} className="admin-login-form"><label>Invited email address<input type="email" value={recoveryEmail} onChange={e=>setRecoveryEmail(e.target.value)} required/></label><button className="admin-primary" disabled={loading}>{loading?"Sending…":"Send new setup link"}</button></form>}<a href="/admin/login" className="admin-back">← Back to sign in</a><a href="/" className="admin-back">Back to nyuperu.org</a></section></main>
}
