"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
import { galleryImageUrl } from "../../lib/mediaUrl";

type Subscriber={id:string;email:string;name:string;status:"subscribed"|"unsubscribed";signup_source:string;consent_at:string};
type Campaign={id:string;subject:string;preview_text:string;html_content:string;status:"draft"|"scheduled"|"sending"|"sent"|"failed";created_at:string;sent_at:string|null};
type EventItem={id:string;title:string;date:string;time:string;location:string;description:string;image:string;rsvpUrl:string;status:string};
type GalleryItem={id:string;title:string;image:string;description:string;sourceUrl?:string;mediaType?:"image"|"video";createdAt?:string};
type SiteContent={events:EventItem[];gallery:GalleryItem[];settings:{clubName:string;shortName:string;email:string;instagram:string;linkedin:string}};
type TemplateKey="monthly"|"events"|"recap"|"announcement";

const templateCopy:Record<TemplateKey,{label:string;subject:string;preview:string;heading:string;intro:string;closing:string}>={
  monthly:{label:"Monthly update",subject:"What’s happening with our community",preview:"Upcoming events, recent moments and what’s next.",heading:"Here’s what’s happening.",intro:"A quick look at what’s coming up, what our community has been doing, and ways to stay connected.",closing:"We hope to see you at an upcoming event. Thank you for being part of our community."},
  events:{label:"Upcoming events",subject:"Upcoming events you won’t want to miss",preview:"Save the dates and join us at our next events.",heading:"Save the dates.",intro:"Here are the next opportunities to connect, celebrate and experience Peruvian culture with us.",closing:"Bring a friend and come be part of it. We’ll see you there."},
  recap:{label:"Community recap",subject:"A look back at recent moments",preview:"Photos and highlights from our recent community programming.",heading:"Recent moments together.",intro:"From conversations to culture, food and community, here are a few moments worth revisiting.",closing:"More is coming soon. Follow along and stay connected for the next gathering."},
  announcement:{label:"Big announcement",subject:"An update from our club",preview:"Important news from our community.",heading:"We have something to share.",intro:"We’re excited to share an important update with our community.",closing:"Thank you for supporting the club and helping us continue building community at NYU."},
};
const htmlEntities:Record<string,string>={"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"};
function esc(value:string){return value.replace(/[&<>"']/g,(c)=>htmlEntities[c]||c);}
function fmtDate(value:string){if(!value)return "Date TBA";const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"});}
function fmtTime(value:string){if(!value)return "";const [h,m]=value.split(":").map(Number);if(Number.isNaN(h))return value;const d=new Date();d.setHours(h,m||0);return d.toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});}

export default function NewsletterAdmin(){
  const [subscribers,setSubscribers]=useState<Subscriber[]>([]);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [site,setSite]=useState<SiteContent>({events:[],gallery:[],settings:{clubName:"NYU Peruvian Student Association",shortName:"NYU Perú",email:"peru@nyu.edu",instagram:"",linkedin:""}});
  const [template,setTemplate]=useState<TemplateKey>("monthly");
  const [subject,setSubject]=useState(templateCopy.monthly.subject);
  const [preview,setPreview]=useState(templateCopy.monthly.preview);
  const [heading,setHeading]=useState(templateCopy.monthly.heading);
  const [intro,setIntro]=useState(templateCopy.monthly.intro);
  const [closing,setClosing]=useState(templateCopy.monthly.closing);
  const [ctaLabel,setCtaLabel]=useState("Visit the club website");
  const [selectedEvents,setSelectedEvents]=useState<string[]>([]);
  const [selectedGallery,setSelectedGallery]=useState<string[]>([]);
  const [galleryDays,setGalleryDays]=useState<number>(30);
  const [message,setMessage]=useState("");
  const [loading,setLoading]=useState(false);
  const [advanced,setAdvanced]=useState(false);
  const [htmlOverride,setHtmlOverride]=useState("");

  async function load(){
    const supabase=createSupabaseBrowserClient();
    const [{data:subs,error:subError},{data:camps,error:campError},contentResponse]=await Promise.all([
      supabase.from("newsletter_subscribers").select("id,email,name,status,signup_source,consent_at").order("consent_at",{ascending:false}),
      supabase.from("newsletter_campaigns").select("id,subject,preview_text,html_content,status,created_at,sent_at").order("created_at",{ascending:false}),
      fetch("/api/admin/content",{cache:"no-store"}),
    ]);
    const contentData=await contentResponse.json().catch(()=>({}));
    if(subError||campError||!contentResponse.ok) return setMessage(subError?.message||campError?.message||contentData.error||"Unable to load newsletter data.");
    setSubscribers((subs||[]) as Subscriber[]);
    setCampaigns((camps||[]) as Campaign[]);
    setSite(contentData.content as SiteContent);
  }
  useEffect(()=>{void load()},[]);

  const active=subscribers.filter(s=>s.status==="subscribed").length;
  const availableEvents=useMemo(()=>site.events.filter(e=>e.status==="published").sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999")),[site.events]);
  const filteredGallery=useMemo(()=>{
    const cutoff=galleryDays===0?null:new Date(Date.now()-galleryDays*86400000);
    return site.gallery.filter(g=>g.mediaType!=="video"&&g.image&&(!cutoff||!g.createdAt||new Date(g.createdAt)>=cutoff));
  },[site.gallery,galleryDays]);
  const chosenEvents=availableEvents.filter(e=>selectedEvents.includes(e.id));
  const chosenGallery=filteredGallery.filter(g=>selectedGallery.includes(g.id));

  function futureEventIds(){const now=new Date();now.setHours(0,0,0,0);return availableEvents.filter(e=>!e.date||new Date(`${e.date}T12:00:00`)>=now).slice(0,4).map(e=>e.id);}
  function applyTemplate(key:TemplateKey){
    const t=templateCopy[key];setTemplate(key);setSubject(t.subject);setPreview(t.preview);setHeading(t.heading);setIntro(t.intro);setClosing(t.closing);setAdvanced(false);setHtmlOverride("");
    if(key==="events") setSelectedEvents(futureEventIds());
    if(key==="recap") setSelectedGallery(filteredGallery.slice(0,6).map(g=>g.id));
  }
  function toggleEvent(id:string){setSelectedEvents(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
  function toggleGallery(id:string){setSelectedGallery(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}

  function generatedHtml(){
    const origin=typeof window!=="undefined"?window.location.origin:"";
    const brand=site.settings.shortName||site.settings.clubName||"NYU Perú";
    const eventHtml=chosenEvents.length?`<tr><td style="padding:10px 32px 8px"><h2 style="font-family:Georgia,serif;font-size:28px;margin:0;color:#171412">Coming up</h2></td></tr>${chosenEvents.map(e=>`<tr><td style="padding:10px 32px"><table role="presentation" width="100%" style="border-collapse:collapse;border:1px solid #e7ded4;border-radius:14px;background:#fff"><tr>${e.image?`<td width="150" style="padding:0"><img src="${esc(galleryImageUrl(e.image))}" alt="" width="150" style="width:150px;height:130px;object-fit:cover;display:block;border-radius:14px 0 0 14px"></td>`:""}<td style="padding:18px"><div style="font-family:Arial,sans-serif;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#c91525">${esc(fmtDate(e.date))}${e.time?` · ${esc(fmtTime(e.time))}`:""}</div><h3 style="font-family:Georgia,serif;font-size:22px;margin:6px 0;color:#171412">${esc(e.title)}</h3><p style="font-family:Arial,sans-serif;font-size:14px;line-height:1.5;color:#625b55;margin:0 0 8px">${esc(e.location||"")}</p>${e.description?`<p style="font-family:Arial,sans-serif;font-size:14px;line-height:1.55;color:#625b55;margin:0">${esc(e.description.slice(0,220))}${e.description.length>220?"…":""}</p>`:""}${e.rsvpUrl?`<p style="margin:14px 0 0"><a href="${esc(e.rsvpUrl)}" style="font-family:Arial,sans-serif;color:#c91525;font-weight:700">RSVP / details →</a></p>`:""}</td></tr></table></td></tr>`).join("")}:"";
    const galleryHtml=chosenGallery.length?`<tr><td style="padding:22px 32px 8px"><h2 style="font-family:Georgia,serif;font-size:28px;margin:0 0 14px;color:#171412">From the community</h2><table role="presentation" width="100%" style="border-collapse:collapse"><tr>${chosenGallery.slice(0,3).map(g=>`<td width="33.33%" style="padding:3px"><img src="${esc(galleryImageUrl(g.image))}" alt="${esc(g.title||"")}" width="180" style="width:100%;height:150px;object-fit:cover;display:block;border-radius:10px"></td>`).join("")}</tr>${chosenGallery.length>3?`<tr>${chosenGallery.slice(3,6).map(g=>`<td width="33.33%" style="padding:3px"><img src="${esc(galleryImageUrl(g.image))}" alt="${esc(g.title||"")}" width="180" style="width:100%;height:150px;object-fit:cover;display:block;border-radius:10px"></td>`).join("")}</tr>`:""}</table></td></tr>`:"";
    return `<!doctype html><html><body style="margin:0;background:#f4ede4"><div style="display:none;max-height:0;overflow:hidden">${esc(preview)}</div><table role="presentation" width="100%" style="border-collapse:collapse;background:#f4ede4"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="640" style="width:100%;max-width:640px;border-collapse:collapse;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="background:#c91525;padding:28px 32px;color:#fff"><div style="font-family:Arial,sans-serif;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase">${esc(site.settings.clubName||brand)}</div><div style="font-family:Georgia,serif;font-size:38px;font-weight:700;margin-top:5px">${esc(brand)}</div></td></tr><tr><td style="padding:34px 32px 18px"><h1 style="font-family:Georgia,serif;font-size:38px;line-height:1.05;color:#171412;margin:0 0 18px">${esc(heading)}</h1><p style="font-family:Arial,sans-serif;font-size:17px;line-height:1.65;color:#625b55;margin:0">${esc(intro)}</p></td></tr>${eventHtml}${galleryHtml}<tr><td style="padding:26px 32px"><p style="font-family:Arial,sans-serif;font-size:16px;line-height:1.65;color:#625b55;margin:0 0 22px">${esc(closing)}</p><a href="${esc(origin)}" style="display:inline-block;background:#c91525;color:white;text-decoration:none;font-family:Arial,sans-serif;font-weight:700;padding:14px 20px;border-radius:8px">${esc(ctaLabel)}</a></td></tr><tr><td style="padding:24px 32px;background:#181514;color:#bdb5af;font-family:Arial,sans-serif;font-size:12px;line-height:1.6"><b style="color:white">${esc(site.settings.clubName||brand)}</b><br>${site.settings.email?esc(site.settings.email):""}<br><br>You’re receiving this because you subscribed to club updates. An unsubscribe link is included automatically when this campaign is sent.</td></tr></table></td></tr></table></body></html>`;
  }
  const html=advanced&&htmlOverride.trim()?htmlOverride:generatedHtml();

  async function createCampaign(event:FormEvent){event.preventDefault();if(!subject.trim())return setMessage("Add a subject first.");setLoading(true);setMessage("Saving draft…");const supabase=createSupabaseBrowserClient();const {error}=await supabase.from("newsletter_campaigns").insert({subject:subject.trim(),preview_text:preview.trim(),html_content:html,status:"draft"});setLoading(false);if(error)return setMessage(error.message);setMessage("Draft saved. You can review it below before sending.");await load();}
  async function sendCampaign(campaign:Campaign){if(!confirm(`Send “${campaign.subject}” to ${active} active subscriber${active===1?"":"s"}?`))return;setLoading(true);setMessage("Sending newsletter…");const supabase=createSupabaseBrowserClient();const {data,error}=await supabase.functions.invoke("send-newsletter",{body:{campaignId:campaign.id,siteOrigin:window.location.origin}});setLoading(false);if(error||data?.error)return setMessage(data?.error||error?.message||"Send failed.");setMessage(`Sent ${data.sent} email${data.sent===1?"":"s"}${data.failed?`; ${data.failed} failed`:""}.`);await load();}
  async function setSubscriberStatus(subscriber:Subscriber,status:"subscribed"|"unsubscribed"){const supabase=createSupabaseBrowserClient();const {error}=await supabase.from("newsletter_subscribers").update({status,unsubscribed_at:status==="unsubscribed"?new Date().toISOString():null}).eq("id",subscriber.id);if(error)return setMessage(error.message);await load();}

  return <main style={{minHeight:"100vh",background:"#f4ede4",padding:"24px 14px 70px",fontFamily:"var(--font-sans)"}}><div style={{maxWidth:1280,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"center",marginBottom:24,flexWrap:"wrap"}}><div><span className="admin-kicker">Communications studio</span><h1 style={{fontFamily:"var(--font-display)",fontSize:"clamp(2.4rem,6vw,4.5rem)",margin:"4px 0"}}>Newsletter</h1><p style={{margin:0,opacity:.72,maxWidth:660}}>Build complete campaigns from existing events, gallery media and club content—without writing HTML.</p></div><a href="/admin" className="admin-primary" style={{textDecoration:"none"}}>← Board CMS</a></div>
    {message&&<div className="cms-notice" style={{marginBottom:18}}>{message}</div>}
    <div className="cms-stats" style={{marginBottom:20}}><article><b>{active}</b><span>Active subscribers</span></article><article><b>{subscribers.length-active}</b><span>Unsubscribed</span></article><article><b>{campaigns.length}</b><span>Campaigns</span></article><article><b>{campaigns.filter(c=>c.status==="sent").length}</b><span>Sent</span></article></div>
    <section className="cms-panel" style={{marginBottom:18}}><span className="admin-kicker">1 · Start with a format</span><h2>Choose a newsletter type</h2><div className="quick-grid">{(Object.keys(templateCopy) as TemplateKey[]).map(k=><button type="button" key={k} onClick={()=>applyTemplate(k)} style={{borderColor:template===k?"#c91525":undefined,background:template===k?"#fff7f7":undefined}}><b>{templateCopy[k].label}</b><span>{templateCopy[k].preview}</span></button>)}</div></section>
    <form onSubmit={createCampaign}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1.05fr) minmax(320px,.95fr)",gap:18,alignItems:"start"}} className="newsletter-builder-grid"><div>
      <section className="cms-panel form-stack"><span className="admin-kicker">2 · Message</span><h2>Write the core message</h2><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label><label>Inbox preview text<input value={preview} onChange={e=>setPreview(e.target.value)}/></label><label>Email headline<input value={heading} onChange={e=>setHeading(e.target.value)}/></label><label>Introduction<textarea value={intro} onChange={e=>setIntro(e.target.value)}/></label><label>Closing note<textarea value={closing} onChange={e=>setClosing(e.target.value)}/></label><label>Bottom button text<input value={ctaLabel} onChange={e=>setCtaLabel(e.target.value)}/></label></section>
      <section className="cms-panel"><span className="admin-kicker">3 · Events</span><h2>Pull from your event calendar</h2><p>Select any published events. Their date, time, location, description, image and RSVP link are inserted automatically.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}><button type="button" onClick={()=>setSelectedEvents(futureEventIds())}>Use next 4 events</button><button type="button" onClick={()=>setSelectedEvents([])}>Clear</button></div><div style={{display:"grid",gap:9}}>{availableEvents.map(e=><label key={e.id} style={{display:"grid",gridTemplateColumns:"24px 1fr",gap:10,alignItems:"start",padding:12,border:"1px solid #e2ddd5",borderRadius:12,background:selectedEvents.includes(e.id)?"#fff7f7":"#fff"}}><input type="checkbox" checked={selectedEvents.includes(e.id)} onChange={()=>toggleEvent(e.id)}/><span><b>{e.title}</b><small style={{display:"block",marginTop:3,opacity:.65}}>{fmtDate(e.date)}{e.location?` · ${e.location}`:""}</small></span></label>)}</div>{!availableEvents.length&&<p className="empty-state">No published events are available yet.</p>}</section>
      <section className="cms-panel"><span className="admin-kicker">4 · Gallery</span><h2>Add recent photos</h2><p>Filter by when media was added to the gallery, then choose the images you want in this email.</p><div className="field-grid"><label>Gallery timeframe<select value={galleryDays} onChange={e=>{setGalleryDays(Number(e.target.value));setSelectedGallery([])}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={0}>All gallery images</option></select></label><label>Quick selection<select onChange={e=>{const n=Number(e.target.value);if(n)setSelectedGallery(filteredGallery.slice(0,n).map(g=>g.id))}} defaultValue=""><option value="">Choose…</option><option value="3">Use first 3</option><option value="6">Use first 6</option></select></label></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(130px,1fr))",gap:10,marginTop:16}}>{filteredGallery.map(g=><button type="button" key={g.id} onClick={()=>toggleGallery(g.id)} style={{padding:6,border:selectedGallery.includes(g.id)?"3px solid #c91525":"1px solid #ddd",borderRadius:12,background:"white",textAlign:"left"}}><img src={galleryImageUrl(g.image)} alt="" style={{width:"100%",aspectRatio:"1",objectFit:"cover",borderRadius:8,display:"block"}}/><span style={{display:"block",fontSize:11,fontWeight:700,padding:"7px 3px 3px"}}>{g.title||"Gallery image"}</span></button>)}</div>{!filteredGallery.length&&<p className="empty-state">No images match this timeframe.</p>}</section>
      <section className="cms-panel form-stack"><button type="button" onClick={()=>{setAdvanced(v=>!v);if(!htmlOverride)setHtmlOverride(generatedHtml())}}>{advanced?"Hide advanced HTML":"Advanced HTML override"}</button>{advanced&&<><p>Optional: edit the generated HTML directly. Once this field has content, it becomes the saved email body.</p><textarea value={htmlOverride} onChange={e=>setHtmlOverride(e.target.value)} rows={18}/></>}<button className="admin-primary" disabled={loading} type="submit">{loading?"Saving…":"Save campaign draft"}</button></section>
    </div><aside style={{position:"sticky",top:18}}><section className="cms-panel"><span className="admin-kicker">Live email preview</span><h2>{subject||"Untitled newsletter"}</h2><p style={{fontSize:13,opacity:.65}}>{chosenEvents.length} event{chosenEvents.length===1?"":"s"} · {chosenGallery.length} photo{chosenGallery.length===1?"":"s"} · {active} active recipients</p><iframe title="Newsletter preview" srcDoc={html} style={{width:"100%",height:720,border:"1px solid #ddd",borderRadius:12,background:"white"}}/></section></aside></div></form>
    <section className="cms-panel" style={{marginTop:18}}><div className="cms-panel-head"><div><span className="admin-kicker">Campaigns</span><h2>Drafts & history</h2></div></div><div style={{display:"grid",gap:10}}>{campaigns.map(c=><article key={c.id} style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",padding:"14px 0",borderTop:"1px solid rgba(0,0,0,.09)",flexWrap:"wrap"}}><div><b>{c.subject}</b><div style={{fontSize:13,opacity:.6}}>{c.status} · {new Date(c.created_at).toLocaleDateString()}{c.sent_at?` · sent ${new Date(c.sent_at).toLocaleDateString()}`:""}</div></div><button className="admin-primary" disabled={loading||c.status==="sending"} onClick={()=>sendCampaign(c)}>{c.status==="sent"?"Send again":"Send now"}</button></article>)}</div>{!campaigns.length&&<p className="empty-state">No newsletters yet.</p>}</section>
    <section className="cms-panel"><div className="cms-panel-head"><div><span className="admin-kicker">Audience</span><h2>Subscribers</h2></div><b>{active} active</b></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720}}><thead><tr><th style={{textAlign:"left",padding:"10px 8px"}}>Subscriber</th><th style={{textAlign:"left",padding:"10px 8px"}}>Source</th><th style={{textAlign:"left",padding:"10px 8px"}}>Joined</th><th style={{textAlign:"left",padding:"10px 8px"}}>Status</th></tr></thead><tbody>{subscribers.map(s=><tr key={s.id} style={{borderTop:"1px solid rgba(0,0,0,.08)"}}><td style={{padding:"12px 8px"}}><b>{s.name||"—"}</b><br/><span style={{fontSize:13,opacity:.68}}>{s.email}</span></td><td style={{padding:"12px 8px"}}>{s.signup_source}</td><td style={{padding:"12px 8px"}}>{new Date(s.consent_at).toLocaleDateString()}</td><td style={{padding:"12px 8px"}}><select value={s.status} onChange={e=>setSubscriberStatus(s,e.target.value as Subscriber["status"])}><option value="subscribed">Subscribed</option><option value="unsubscribed">Unsubscribed</option></select></td></tr>)}</tbody></table></div>{!subscribers.length&&<p className="empty-state">No newsletter subscribers yet.</p>}</section>
  </div><style>{`@media(max-width:900px){.newsletter-builder-grid{grid-template-columns:1fr!important}.newsletter-builder-grid aside{position:static!important}}`}</style></main>;
}
