"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
import { galleryImageUrl } from "../../lib/mediaUrl";
import { buildNewsletterHtml, formatEventDate, type NewsletterEvent, type NewsletterGalleryItem, type NewsletterSettings } from "./emailBuilder";

type Subscriber={id:string;email:string;name:string;status:"subscribed"|"unsubscribed";signup_source:string;consent_at:string};
type Campaign={id:string;subject:string;preview_text:string;html_content:string;status:"draft"|"scheduled"|"sending"|"sent"|"failed";created_at:string;sent_at:string|null;scheduled_for?:string|null};
type Delivery={campaign_id:string;status:string;opened_at:string|null;clicked_at:string|null};
type SiteContent={events:NewsletterEvent[];gallery:NewsletterGalleryItem[];settings:NewsletterSettings};
type TemplateKey="monthly"|"events"|"recap"|"announcement";
const templates:Record<TemplateKey,{label:string;description:string;subject:string;preview:string;heading:string;intro:string;closing:string}>={monthly:{label:"Monthly update",description:"Events + recent photos + club update",subject:"What’s happening with our community",preview:"Upcoming events, recent moments and what’s next.",heading:"Here’s what’s happening.",intro:"A quick look at what’s coming up, what our community has been doing, and ways to stay connected.",closing:"We hope to see you at an upcoming event. Thank you for being part of our community."},events:{label:"Upcoming events",description:"A clean digest of the next events",subject:"Upcoming events you won’t want to miss",preview:"Save the dates and join us at our next events.",heading:"Save the dates.",intro:"Here are the next opportunities to connect, celebrate and experience Peruvian culture with us.",closing:"Bring a friend and come be part of it. We’ll see you there."},recap:{label:"Community recap",description:"Recent gallery highlights and community moments",subject:"A look back at recent moments",preview:"Photos and highlights from recent programming.",heading:"Recent moments together.",intro:"From conversations to culture, food and community, here are a few moments worth revisiting.",closing:"More is coming soon. Follow along and stay connected for the next gathering."},announcement:{label:"Big announcement",description:"One focused message with optional event/media blocks",subject:"An update from our club",preview:"Important news from our community.",heading:"We have something to share.",intro:"We’re excited to share an important update with our community.",closing:"Thank you for supporting the club and helping us continue building community at NYU."}};

export default function NewsletterAdmin(){
 const[subscribers,setSubscribers]=useState<Subscriber[]>([]);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[deliveries,setDeliveries]=useState<Delivery[]>([]);const[site,setSite]=useState<SiteContent>({events:[],gallery:[],settings:{clubName:"NYU Peruvian Student Association",shortName:"NYU Perú",email:"peru@nyu.edu",instagram:"",linkedin:""}});const[template,setTemplate]=useState<TemplateKey>("monthly");const[subject,setSubject]=useState(templates.monthly.subject);const[preview,setPreview]=useState(templates.monthly.preview);const[heading,setHeading]=useState(templates.monthly.heading);const[intro,setIntro]=useState(templates.monthly.intro);const[closing,setClosing]=useState(templates.monthly.closing);const[ctaLabel,setCtaLabel]=useState("Visit the club website");const[selectedEvents,setSelectedEvents]=useState<string[]>([]);const[selectedGallery,setSelectedGallery]=useState<string[]>([]);const[galleryDays,setGalleryDays]=useState(30);const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[testEmail,setTestEmail]=useState("");const[scheduleAt,setScheduleAt]=useState("");
 async function load(){const s=createSupabaseBrowserClient();const[{data:subs,error:se},{data:camps,error:ce},{data:dels,error:de},r]=await Promise.all([s.from("newsletter_subscribers").select("id,email,name,status,signup_source,consent_at").order("consent_at",{ascending:false}),s.from("newsletter_campaigns").select("id,subject,preview_text,html_content,status,created_at,sent_at,scheduled_for").order("created_at",{ascending:false}),s.from("newsletter_deliveries").select("campaign_id,status,opened_at,clicked_at"),fetch("/api/admin/content",{cache:"no-store"})]);const d=await r.json().catch(()=>({}));if(se||ce||de||!r.ok){setMessage(se?.message||ce?.message||de?.message||d.error||"Unable to load newsletter data.");return}setSubscribers((subs||[]) as Subscriber[]);setCampaigns((camps||[]) as Campaign[]);setDeliveries((dels||[]) as Delivery[]);setSite(d.content as SiteContent)}
 useEffect(()=>{void load()},[]);
 const active=subscribers.filter(s=>s.status==="subscribed").length;const availableEvents=useMemo(()=>site.events.filter(e=>e.status==="published").sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999")),[site.events]);const filteredGallery=useMemo(()=>{const cutoff=galleryDays===0?null:new Date(Date.now()-galleryDays*86400000);return site.gallery.filter(g=>g.mediaType!=="video"&&g.image&&(!cutoff||!g.createdAt||new Date(g.createdAt)>=cutoff))},[site.gallery,galleryDays]);const chosenEvents=availableEvents.filter(e=>selectedEvents.includes(e.id));const chosenGallery=filteredGallery.filter(g=>selectedGallery.includes(g.id));
 const futureIds=()=>{const now=new Date();now.setHours(0,0,0,0);return availableEvents.filter(e=>!e.date||new Date(`${e.date}T12:00:00`)>=now).slice(0,4).map(e=>e.id)};
 function applyTemplate(k:TemplateKey){const t=templates[k];setTemplate(k);setSubject(t.subject);setPreview(t.preview);setHeading(t.heading);setIntro(t.intro);setClosing(t.closing);if(k==="events")setSelectedEvents(futureIds());if(k==="recap")setSelectedGallery(filteredGallery.slice(0,6).map(g=>g.id))}
 const html=buildNewsletterHtml({origin:typeof window!=="undefined"?window.location.origin:"",settings:site.settings,preview,heading,intro,closing,ctaLabel,events:chosenEvents,gallery:chosenGallery});
 async function saveDraft(e:FormEvent){e.preventDefault();if(!subject.trim())return;setLoading(true);const s=createSupabaseBrowserClient();const{error}=await s.from("newsletter_campaigns").insert({subject:subject.trim(),preview_text:preview.trim(),html_content:html,status:"draft"});setLoading(false);setMessage(error?error.message:"Draft saved. Test it, schedule it, or send it from Campaign History.");if(!error)await load()}
 async function invoke(c:Campaign,body:Record<string,unknown>,label:string){setLoading(true);setMessage(label);const s=createSupabaseBrowserClient();const{data,error}=await s.functions.invoke("send-newsletter",{body:{campaignId:c.id,siteOrigin:window.location.origin,...body}});setLoading(false);if(error||data?.error){setMessage(data?.error||error?.message||"Request failed.");return false}setMessage(data.test?"Test email sent.":data.scheduled?`Scheduled ${data.sent} email${data.sent===1?"":"s"}.`:`Sent ${data.sent} email${data.sent===1?"":"s"}${data.failed?`; ${data.failed} failed`:""}.`);await load();return true}
 async function send(c:Campaign){if(confirm(`Send “${c.subject}” to ${active} active subscribers now?`))await invoke(c,{},"Sending newsletter…")}
 async function schedule(c:Campaign){if(!scheduleAt){setMessage("Choose a date and time first.");return}const when=new Date(scheduleAt);if(Number.isNaN(when.getTime()))return setMessage("Choose a valid schedule time.");if(confirm(`Schedule “${c.subject}” for ${when.toLocaleString()}?`))await invoke(c,{scheduledAt:when.toISOString()},"Scheduling newsletter…")}
 async function test(c:Campaign){if(!testEmail.trim())return setMessage("Enter a test email address first.");await invoke(c,{testEmail:testEmail.trim()},"Sending test email…")}
 async function duplicate(c:Campaign){const s=createSupabaseBrowserClient();const{error}=await s.from("newsletter_campaigns").insert({subject:`Copy of ${c.subject}`,preview_text:c.preview_text,html_content:c.html_content,status:"draft"});setMessage(error?error.message:"Campaign duplicated as a draft.");if(!error)await load()}
 async function status(sub:Subscriber,status:"subscribed"|"unsubscribed"){const s=createSupabaseBrowserClient();const{error}=await s.from("newsletter_subscribers").update({status,unsubscribed_at:status==="unsubscribed"?new Date().toISOString():null}).eq("id",sub.id);setMessage(error?error.message:"Subscriber updated.");if(!error)await load()}
 function metrics(id:string){const d=deliveries.filter(x=>x.campaign_id===id),sent=d.filter(x=>x.status==="sent"||x.status==="scheduled").length,opened=d.filter(x=>x.opened_at).length,clicked=d.filter(x=>x.clicked_at).length;return{sent,opened,clicked}}
 return <main className="newsletter-admin-page"><div className="newsletter-admin-wrap"><header className="newsletter-admin-head"><div><span className="admin-kicker">Communications studio</span><h1>Newsletter</h1><p>Build campaigns from live events and gallery media, test them, schedule them, and measure performance.</p></div><a href="/admin" className="admin-primary">← Board CMS</a></header>{message&&<div className="cms-notice">{message}</div>}
 <div className="cms-stats"><article><b>{active}</b><span>Active subscribers</span></article><article><b>{campaigns.length}</b><span>Campaigns</span></article><article><b>{campaigns.filter(c=>c.status==="scheduled").length}</b><span>Scheduled</span></article><article><b>{deliveries.filter(d=>d.opened_at).length}</b><span>Email opens</span></article></div>
 <section className="cms-panel"><span className="admin-kicker">1 · Format</span><h2>Start with a template</h2><div className="quick-grid">{(Object.keys(templates) as TemplateKey[]).map(k=><button type="button" key={k} onClick={()=>applyTemplate(k)} className={template===k?"selected-option":""}><b>{templates[k].label}</b><span>{templates[k].description}</span></button>)}</div></section>
 <form onSubmit={saveDraft}><div className="newsletter-builder-grid"><div><section className="cms-panel form-stack"><span className="admin-kicker">2 · Message</span><h2>Write the core message</h2><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label><label>Inbox preview<input value={preview} onChange={e=>setPreview(e.target.value)}/></label><label>Headline<input value={heading} onChange={e=>setHeading(e.target.value)}/></label><label>Introduction<textarea value={intro} onChange={e=>setIntro(e.target.value)}/></label><label>Closing note<textarea value={closing} onChange={e=>setClosing(e.target.value)}/></label><label>Button text<input value={ctaLabel} onChange={e=>setCtaLabel(e.target.value)}/></label></section>
 <section className="cms-panel"><span className="admin-kicker">3 · Events</span><h2>Upcoming events</h2><div className="inline-actions"><button type="button" onClick={()=>setSelectedEvents(futureIds())}>Use next 4</button><button type="button" onClick={()=>setSelectedEvents([])}>Clear</button></div><div className="newsletter-pick-list">{availableEvents.map(e=><label key={e.id}><input type="checkbox" checked={selectedEvents.includes(e.id)} onChange={()=>setSelectedEvents(v=>v.includes(e.id)?v.filter(x=>x!==e.id):[...v,e.id])}/><span><b>{e.title}</b><small>{formatEventDate(e.date)} · {e.location}</small></span></label>)}</div></section>
 <section className="cms-panel"><span className="admin-kicker">4 · Gallery</span><h2>Photos from a timeframe</h2><div className="field-grid"><label>Timeframe<select value={galleryDays} onChange={e=>{setGalleryDays(Number(e.target.value));setSelectedGallery([])}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={0}>All</option></select></label><label>Quick select<select defaultValue="" onChange={e=>{const n=Number(e.target.value);if(n)setSelectedGallery(filteredGallery.slice(0,n).map(g=>g.id))}}><option value="">Choose…</option><option value="3">First 3</option><option value="6">First 6</option></select></label></div><div className="newsletter-photo-picker">{filteredGallery.map(g=><button type="button" key={g.id} className={selectedGallery.includes(g.id)?"selected":""} onClick={()=>setSelectedGallery(v=>v.includes(g.id)?v.filter(x=>x!==g.id):[...v,g.id])}><img src={galleryImageUrl(g.image)} alt=""/><span>{g.title}</span></button>)}</div></section>
 <section className="cms-panel form-stack"><button className="admin-primary" type="submit" disabled={loading}>{loading?"Working…":"Save campaign draft"}</button></section></div><aside className="newsletter-preview-sticky"><section className="cms-panel"><span className="admin-kicker">Live preview</span><h2>{subject}</h2><p>{chosenEvents.length} events · {chosenGallery.length} photos · {active} recipients</p><iframe title="Newsletter preview" srcDoc={html}/></section></aside></div></form>
 <section className="cms-panel newsletter-history"><div><span className="admin-kicker">Campaign history</span><h2>Test, schedule, send & reuse</h2></div><div className="newsletter-send-controls"><label>Test email<input type="email" value={testEmail} onChange={e=>setTestEmail(e.target.value)} placeholder="you@example.com"/></label><label>Schedule time<input type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/></label></div><div className="campaign-list">{campaigns.map(c=>{const m=metrics(c.id);return <article key={c.id}><div><span className="status-pill">{c.status}</span><h3>{c.subject}</h3><small>{c.scheduled_for?`Scheduled ${new Date(c.scheduled_for).toLocaleString()}`:c.sent_at?`Sent ${new Date(c.sent_at).toLocaleString()}`:`Created ${new Date(c.created_at).toLocaleDateString()}`}</small><p>{m.sent} recipients · {m.opened} opened · {m.clicked} clicked</p></div><div className="campaign-actions"><button onClick={()=>test(c)} disabled={loading}>Send test</button><button onClick={()=>duplicate(c)} disabled={loading}>Duplicate</button>{c.status==="draft"||c.status==="failed"?<><button onClick={()=>schedule(c)} disabled={loading}>Schedule</button><button className="admin-primary" onClick={()=>send(c)} disabled={loading}>Send now</button></>:null}</div></article>})}</div></section>
 <section className="cms-panel"><span className="admin-kicker">Subscribers</span><h2>Audience</h2><div className="subscriber-list">{subscribers.map(s=><article key={s.id}><div><b>{s.email}</b><small>{s.name||"No name"} · {s.signup_source}</small></div><button onClick={()=>status(s,s.status==="subscribed"?"unsubscribed":"subscribed")}>{s.status==="subscribed"?"Unsubscribe":"Resubscribe"}</button></article>)}</div></section></div></main>;
}
