"use client";

import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";

type Field={id:string;field_key:string;label:string;field_type:"text"|"textarea"|"select"|"number";placeholder:string;options:string[];required:boolean;team_column:string|null;sort_order:number;active:boolean};
const linked=[{value:"",label:"Custom field only"},{value:"name",label:"Team: name"},{value:"title",label:"Team: position/title"},{value:"board_year",label:"Team: board year"},{value:"bio",label:"Team: bio"},{value:"image_url",label:"Team: image URL"}];
const slug=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");

export default function ActivationSetupEditor(){
 const[fields,setFields]=useState<Field[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function load(){const s=createSupabaseBrowserClient();const{data,error}=await s.from("activation_setup_fields").select("*").order("sort_order");if(error)setMessage(error.message);else setFields((data||[]).map((x:any)=>({...x,options:Array.isArray(x.options)?x.options:[]})));setLoading(false)}
 useEffect(()=>{void load()},[]);
 const patch=(id:string,p:Partial<Field>)=>setFields(v=>v.map(f=>f.id===id?{...f,...p}:f));
 async function add(){const s=createSupabaseBrowserClient();const n=fields.length+1,key=`custom_${Date.now()}`;const{error}=await s.from("activation_setup_fields").insert({field_key:key,label:"New field",field_type:"text",placeholder:"",options:[],required:false,team_column:null,sort_order:n*10,active:true});if(error)setMessage(error.message);else await load()}
 async function remove(field:Field){if(!confirm(`Remove “${field.label}” from account setup? Existing saved answers will remain in account history.`))return;const s=createSupabaseBrowserClient();const{error}=await s.from("activation_setup_fields").delete().eq("id",field.id);setMessage(error?error.message:"Field removed.");if(!error)await load()}
 async function save(){setSaving(true);setMessage("Saving activation form…");const s=createSupabaseBrowserClient();for(const [i,f] of fields.entries()){const key=slug(f.field_key||f.label)||`field_${i+1}`;const{error}=await s.from("activation_setup_fields").update({field_key:key,label:f.label.trim()||"Untitled field",field_type:f.field_type,placeholder:f.placeholder||"",options:f.options||[],required:f.required,team_column:f.team_column||null,sort_order:i*10,active:f.active,updated_at:new Date().toISOString()}).eq("id",f.id);if(error){setSaving(false);return setMessage(error.message)}}setSaving(false);setMessage("Saved. New account activations will use this form immediately.");await load()}
 const move=(index:number,delta:number)=>{const next=[...fields],j=index+delta;if(j<0||j>=next.length)return;[next[index],next[j]]=[next[j],next[index]];setFields(next)};
 if(loading)return <main className="admin-loading">Loading activation setup…</main>;
 return <main className="access-page"><div className="access-wrap"><div className="access-head"><div><span className="admin-kicker">Super Admin</span><h1>Activation / Finish Account Setup</h1><p>Control what new board members must fill out when creating their account. Password and account email are security fields and are always handled automatically.</p></div><a href="/admin" className="admin-primary">← Board CMS</a></div>{message&&<div className="cms-notice">{message}</div>}
 <section className="cms-panel"><div className="cms-panel-head"><div><span className="admin-kicker">Setup form</span><h2>Fields shown during activation</h2></div><div className="actions"><button onClick={add}>＋ Add field</button><button className="admin-primary" onClick={save} disabled={saving}>{saving?"Saving…":"Save setup form"}</button></div></div><div className="editor-list">{fields.map((f,i)=><article className="cms-panel editor-card" key={f.id}><div className="editor-card-head"><div><span className="status-pill">{f.active?"Shown":"Hidden"}</span><h3>{f.label}</h3></div><div className="actions"><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button onClick={()=>move(i,1)} disabled={i===fields.length-1}>↓</button><button className="danger" onClick={()=>remove(f)}>Remove</button></div></div><div className="field-grid"><label>Field label<input value={f.label} onChange={e=>patch(f.id,{label:e.target.value})}/></label><label>Field key<input value={f.field_key} onChange={e=>patch(f.id,{field_key:e.target.value})}/></label><label>Input type<select value={f.field_type} onChange={e=>patch(f.id,{field_type:e.target.value as Field["field_type"]})}><option value="text">Text</option><option value="textarea">Long text</option><option value="number">Number</option><option value="select">Dropdown</option></select></label><label>Team-page connection<select value={f.team_column||""} onChange={e=>patch(f.id,{team_column:e.target.value||null})}>{linked.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Required?<select value={f.required?"yes":"no"} onChange={e=>patch(f.id,{required:e.target.value==="yes"})}><option value="yes">Required</option><option value="no">Optional</option></select></label><label>Shown?<select value={f.active?"yes":"no"} onChange={e=>patch(f.id,{active:e.target.value==="yes"})}><option value="yes">Shown</option><option value="no">Hidden</option></select></label></div><label>Placeholder/help text<input value={f.placeholder} onChange={e=>patch(f.id,{placeholder:e.target.value})}/></label>{f.field_type==="select"&&<label>Dropdown choices <small>comma-separated</small><input value={(f.options||[]).join(", ")} onChange={e=>patch(f.id,{options:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label>}</article>)}</div></section>
 <section className="cms-panel"><span className="admin-kicker">Protected behavior</span><h2>What cannot be accidentally broken</h2><p>Account email comes from the invitation and is not editable here. Password + confirmation remain mandatory security fields for first-time activation. Team-linked fields automatically update the public Team page and its year filter. Custom fields are saved to the member account for future use.</p></section></div></main>;
}
