import Link from "next/link";
import { Footer, Header } from "./components/SiteChrome";
import HomeMediaShowcase from "./components/HomeMediaShowcase";
import NewsletterSignup from "./components/NewsletterSignup";
import { clubMedia, galleryImages } from "./lib/clubMedia";
import { getLiveSiteContent } from "./lib/liveSiteContent";
import { galleryImageUrl } from "./lib/mediaUrl";

export const dynamic="force-dynamic";
const experiences=[["Cultura","Peru in motion","Traditions, history, music, art and identity."],["Comunidad","A place to belong","Socials, collaborations, gatherings and friendships."],["Gastronomía","Taste the story","Food-centered cultural experiences and shared tables."],["Conversaciones","Peruvian voices","Artists, alumni, community leaders and conversations."]];
const photo=(src:string,position="center")=>({backgroundImage:`url(${src})`,backgroundSize:"cover",backgroundPosition:position,backgroundRepeat:"no-repeat"});
const today=new Date().toISOString().slice(0,10);

export default async function HomePage(){
 const site=await getLiveSiteContent();const brand=site.settings.shortName||site.settings.clubName;const heroImage=site.homepage.heroImage||clubMedia.conversation[1];
 const upcoming=site.events.filter(e=>e.status==="published"&&(!e.date||e.date>=today)).sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999"));
 const featured=site.events.find(e=>e.id===site.homepage.featuredEventId)||upcoming[0];
 const imagePool=site.gallery.filter(i=>i.mediaType!=="video");const carouselSlides=(imagePool.length?imagePool:galleryImages).slice(0,8).map((item:any)=>({image:galleryImageUrl(item.image),title:item.title,description:item.description}));
 const featuredMedia=imagePool.filter(i=>i.featured).slice(0,4);
 const organizationJsonLd={"@context":"https://schema.org","@type":"Organization",name:site.settings.clubName,alternateName:brand,url:process.env.NEXT_PUBLIC_SITE_URL||"https://nyu-club-website.vercel.app",email:site.settings.email,sameAs:[site.settings.instagram,site.settings.linkedin].filter(Boolean)};
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(organizationJsonLd)}}/><Header/>
  <section className="home-hero"><div className="hero-photo" style={photo(heroImage,"center 38%")}/><div className="hero-shade"/><div className="wrap hero-content"><span className="kicker light">{site.settings.clubName}</span><h1>{brand.toUpperCase()}</h1><h2>{site.homepage.headline}</h2><p>{site.homepage.description}</p><div className="actions"><Link className="btn red" href="/join">Join our community</Link><Link className="btn outline-light" href="/events">Explore events →</Link></div></div></section>
  <section className="stats"><div className="wrap stats-grid"><div><b>EST.<br/>2016</b></div><div><b>NYU</b><span>Student community</span></div><div><b>NYC</b><span>Culture across the city</span></div><div><b>OPEN</b><span>To the NYU community</span></div></div></section>
  <section className="cream-section"><div className="wrap intro-grid"><div><span className="kicker">Our community</span><h2>More than a club.<br/>A home for Peru at NYU.</h2><p>We are a cultural and social community connecting Peruvians, the Peruvian diaspora, and friends of Peru across NYU and New York City.</p><Link className="btn outline" href="/about">Learn more about us</Link></div><div className="photo-card tall" style={photo(clubMedia.conversation[2])}><span>Community at {brand}</span></div><div className="pillars"><article><i>✦</i><div><h3>Culture</h3><p>Celebrate Peruvian and Andean heritage.</p></div></article><article><i>◎</i><div><h3>Community</h3><p>Connect with Peruvians, the diaspora and the NYU community.</p></div></article><article><i>↗</i><div><h3>Connection</h3><p>Build friendships and relationships across New York.</p></div></article></div></div></section>
  <HomeMediaShowcase slides={carouselSlides} primaryVideoUrl={site.homepage.videoUrl} primaryPosterUrl={site.homepage.videoPosterUrl||clubMedia.conversation[0]} secondaryVideoUrl={site.homepage.secondaryVideoUrl} secondaryPosterUrl={site.homepage.secondaryVideoPosterUrl||clubMedia.conversation[3]}/>
  {!!upcoming.length&&<section className="page-section home-upcoming"><div className="wrap"><div className="section-title"><span className="kicker">Coming up</span><h2>Put it on your calendar.</h2><Link className="text-link" href="/events">All events →</Link></div><div className="home-event-grid">{upcoming.slice(0,3).map(e=><article key={e.id}>{e.image&&<div className="home-event-photo" style={photo(e.image)}/>}<div><span className="kicker">{e.date||"Date TBA"}</span><h3>{e.title}</h3><p>{e.location}</p><Link href={`/events/${encodeURIComponent(e.slug||e.id)}`}>View event →</Link></div></article>)}</div></div></section>}
  {featured&&<section className="cream-section"><div className="wrap"><div className="section-title"><span className="kicker">Featured event</span><h2>Come experience it.</h2></div><article className="feature-event"><div className="event-image" style={photo(featured.image||clubMedia.conversation[0])}/><div className="event-copy"><span className="kicker light">Upcoming</span><h3>{featured.title}</h3><p>{featured.description}</p><ul>{featured.date&&<li>{featured.date}</li>}{featured.time&&<li>{featured.time}</li>}<li>{featured.location}</li></ul><Link href={`/events/${encodeURIComponent(featured.slug||featured.id)}`} className="btn red">View event</Link></div></article></div></section>}
  {!!featuredMedia.length&&<section className="page-section"><div className="wrap"><div className="section-title"><span className="kicker">Featured moments</span><h2>From the community.</h2><Link className="text-link" href="/gallery">Open gallery →</Link></div><div className="home-featured-media">{featuredMedia.map(i=><article key={i.id}><img src={galleryImageUrl(i.image)} alt={i.title}/><span>{i.album||"Club gallery"}</span><h3>{i.title}</h3></article>)}</div></div></section>}
  <section className="cream-section" id="community"><div className="wrap"><div className="section-title"><span className="kicker">What we do</span><h2>Experiences that celebrate Peru.</h2></div><div className="experience-grid">{experiences.map(([title,sub,desc],i)=><article key={title}><div className="experience-img" style={photo(clubMedia.conversation[i%clubMedia.conversation.length])}/><span className="kicker">{sub}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
  <NewsletterSignup/>
  <section className="join-banner"><div className="wrap join-grid"><div><span className="kicker light">Join the community</span><h2>Peru is the connection.<br/>Community is the reason.</h2><p>Peruvian? Peruvian-American? Interested in the culture? Just looking for community? You&apos;re welcome here.</p><div className="actions"><Link className="btn white" href="/join">Join {brand}</Link><a className="btn outline-light" href={site.settings.instagram}>Follow us</a></div></div><div className="nyc-photo" style={photo(clubMedia.conversation[3])}><span>Peru × New York City</span></div></div></section><Footer/>
 </main>;
}
