"use client";

import { useEffect,useMemo,useState } from "react";

type Row={id:string;title:string;status:string;event_date:string|null;approval_status:string;approval_note:string;approved_at:string|null;publish_at:string|null;unpublish_at:string|null;updated_at:string|null};
const local=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
const pretty=(value:string|null)=>value?new Date(value).toLocaleString():"—";

export default function PublishingCenter(){
 const[events,setEvents]=useState<Row[]>([]);const[role,setRole]=useState("");const[loading,setLoading]=useState(true);const[working,setWorking]=useState("");const[msg,setMsg]=useState("");const[filter,setFilter]=useState("all");const[search,setSearch]=useState("");
 const reviewer=role==="super_admin"||role==="admin";
 async function load(){setLoading(true);const r=await fetch("/api/admin/publishing",{cache:"no-store"});const d=await r.json();if(r.ok){setEvents(d.events||[]);setRole(d.role||"")}else setMsg(d.error||"Unable to load publishing queue.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>events.filter(e=>(filter==="all"||e.approval_status===filter||e.status===filter)&&(!search.trim()||e.title.toLowerCase().includes(search.trim().toLowerCase()))),[events,filter,search]);
 const patch=(id:string,p:Partial<Row>)=>setEvents(v=>v.map(x=>x.id===id?{...x,...p}:x));
 async function act(row:Row,action:string){setWorking(row.id+action);setMsg("");const r=await fetch("/api/admin/publishing",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,action,publishAt:row.publish_at,unpublishAt:row.unpublish_at,note:row.approval_note})});const d=await r.json();setWorking("");if(!r.ok){setMsg(d.error||"Update failed.");return}setMsg(action==="publish_now"?"Event published.":action==="approve"?"Event approved and schedule saved.":"Publishing workflow updated.");await load()}
 if(loading)return <main className="admin-loading">Loading Publishing Center…</main>;
 return <main className="newsletter-admin-page"><div className="newsletter-admin-wrap"><header className="newsletter-admin-head"><div><span className="admin-kicker">Review & release</span><h1>Publishing Center</h1><p>Approve event content, schedule when it goes live, and automatically move it out of the live calendar later.</p></div><a href="/admin" className="admin-primary">← Board CMS</a></header>{msg&&<div className="cms-notice">{msg}</div>}
 <div className="cms-stats"><article><b>{events.filter(e=>e.approval_status==="review").length}</b><span>Awaiting review</span></article><article><b>{events.filter(e=>e.approval_status==="approved"&&e.status==="draft").length}</b><span>Approved drafts</span></article><article><b>{events.filter(e=>e.publish_at&&e.status==="draft").length}</b><span>Scheduled</span></article><article><b>{events.filter(e=>e.status==="published").length}</b><span>Live events</span></article></div>
 <section className="cms-panel"><div className="field-grid"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Event title"/></label><label>Filter<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Everything</option><option value="review">Needs review</option><option value="approved">Approved</option><option value="changes_requested">Changes requested</option><option value="draft">Draft</option><option value="published">Published</option><option value="past">Past</option></select></label></div><p><small>Scheduled publishing runs automatically every minute. Only approved drafts are eligible to go live automatically.</small></p></section>
 <div className="editor-list">{visible.map(row=><article className="cms-panel editor-card" key={row.id}><div className="editor-card-head"><div><span className="status-pill">{row.status}</span> <span className="status-pill">{row.approval_status}</span><h2>{row.title}</h2><small>{row.event_date||"No event date"} · Last updated {pretty(row.updated_at)}</small></div></div><div className="field-grid"><label>Publish at<input type="datetime-local" value={local(row.publish_at)} onChange={e=>patch(row.id,{publish_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Move to past at<input type="datetime-local" value={local(row.unpublish_at)} onChange={e=>patch(row.id,{unpublish_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div><label>Review note<textarea rows={3} value={row.approval_note||""} onChange={e=>patch(row.id,{approval_note:e.target.value})} placeholder="Notes for the editor or reviewer"/></label><div className="inline-actions"><button disabled={working.startsWith(row.id)} onClick={()=>act(row,"save_schedule")}>Save schedule</button><button disabled={working.startsWith(row.id)} onClick={()=>act(row,"submit_review")}>Submit for review</button>{reviewer&&<><button disabled={working.startsWith(row.id)} onClick={()=>act(row,"approve")}>Approve</button><button disabled={working.startsWith(row.id)} onClick={()=>act(row,"request_changes")}>Request changes</button><button className="admin-primary" disabled={working.startsWith(row.id)} onClick={()=>act(row,"publish_now")}>Publish now</button><button className="danger" disabled={working.startsWith(row.id)} onClick={()=>act(row,"return_to_draft")}>Return to draft</button></>}<button disabled={working.startsWith(row.id)} onClick={()=>act(row,"cancel_schedule")}>Clear schedule</button></div>{row.approved_at&&<small>Approved {pretty(row.approved_at)}</small>}</article>)}</div>
 {!visible.length&&<section className="cms-panel"><h2>No events match this view.</h2></section>}
 </div></main>;
}
