import type { Metadata } from "next";
import { Footer, Header, PageHero } from "../components/SiteChrome";
import InstagramSection from "../components/InstagramSection";
import { archiveEvents, galleryImages } from "../lib/clubMedia";
import { getLiveSiteContent } from "../lib/liveSiteContent";
import { getPublicPageSettings,pageCopy } from "../lib/publicPageSettings";
import GalleryBrowser from "./GalleryBrowser";

export async function generateMetadata():Promise<Metadata>{const site=await getLiveSiteContent();const formal=site.settings.clubName||"NYU Peruvian Student Association";return{title:`Gallery | ${formal}`,description:"Browse photos, videos, Instagram highlights and sourced archive media from NYU Peruvian Student Association events and community programming."};}
export const dynamic="force-dynamic";
const photo=(src:string,position="center")=>({backgroundImage:`url(${src})`,backgroundSize:"cover",backgroundPosition:position,backgroundRepeat:"no-repeat"});
export default async function GalleryPage(){const site=await getLiveSiteContent();const brand=site.settings.shortName||site.settings.clubName||"NYU Perú";const page=await getPublicPageSettings("gallery",{eyebrow:"Gallery",title:"Memories that connect us.",subtitle:`A growing archive of the people, events and experiences that make ${brand} what it is.`});const eventTitles=Object.fromEntries(site.events.map(e=>[e.id,e.title]));const media=((site.settings.cmsConfig||{}) as any).media||{};const home=((site.settings.cmsConfig||{}) as any).homepage||{};const layoutClass=`page-layout-${page.layout.heroAlign} page-layout-${page.layout.contentWidth} page-spacing-${page.layout.sectionSpacing}`;return <main className={layoutClass}><Header/><PageHero eyebrow={page.eyebrow} title={page.title.replaceAll("{{brand}}",brand)} subtitle={page.subtitle.replaceAll("{{brand}}",brand)}/>{site.gallery.length>0&&<section className="page-section"><div className="wrap gallery-intro"><div><span className="kicker">Club media library</span><h2>{pageCopy(page,"libraryHeading","Photos and videos managed by the board.")}</h2></div><p>{pageCopy(page,"libraryBody","Filter by year, album or media type. Featured items can also appear across the site and in newsletter campaigns.")}</p></div><div className="wrap"><GalleryBrowser items={site.gallery} eventTitles={eventTitles} options={media}/></div></section>}{home.showInstagram!==false&&<InstagramSection/>}<section className="page-section archive-media-section"><div className="wrap gallery-intro"><div><span className="kicker">Verified public archive</span><h2>{pageCopy(page,"archiveHeading","Photos with their story attached.")}</h2></div><p>{pageCopy(page,"archiveBody","These sourced records preserve the captions and references we could verify from the club's public posts.")}</p></div><div className="wrap sourced-gallery">{galleryImages.map(item=><article key={item.id} className="sourced-card"><div className="sourced-photo" style={item.atlasPosition?{...photo(item.image,item.atlasPosition),backgroundSize:"200% 200%"}:photo(item.image)} role="img" aria-label={item.title}/><div className="sourced-copy"><span className="kicker">{item.source}</span><h2>{item.title}</h2>{media.showCaptions!==false&&<p>{item.description}</p>}<a href={item.sourceUrl} target="_blank" rel="noreferrer" className="source-link">View source ↗</a></div></article>)}</div></section><section className="archive-section"><div className="wrap archive-head"><span className="kicker light">Club archive</span><h2>{pageCopy(page,"recordHeading","More events in the public record.")}</h2><p>{pageCopy(page,"recordBody","These records are preserved while the board continues adding photos, captions and fuller event details.")}</p></div><div className="wrap archive-grid">{archiveEvents.map(item=><article key={item.title}>{media.showDates!==false&&<span className="kicker light">{item.date}</span>}<h3>{item.title}</h3><p>{item.source}</p></article>)}</div></section><Footer/></main>}
