"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
type Role="super_admin"|"admin"|"events_manager"|"media_manager"|"team_manager"|"viewer";
type Profile={id:string;email:string;display_name:string|null;role:Role;status:"invited"|"active"|"disabled";created_at:string;last_seen_at:string|null};
type Audit={id:number;actor_id:string|null;action:string;created_at:string;metadata:Record<string,unknown>|null};
const SITE_ORIGIN="https://nyuperu.org";
const RESEND_COOLDOWN_MS=60_000;
const roles:{value:Role;label:string}[]=[{value:"super_admin",label:"Super Admin"},{value:"admin",label:"Admin"},{value:"events_manager",label:"Events Manager"},{value:"media_manager",label:"Media Manager"},{value:"team_manager",label:"Team Manager"},{value:"viewer",label:"Viewer"}];
const permissions=[{role:"Super Admin",scope:"Everything",details:"Full CMS access, users, roles, Super Admin assignments, newsletter, analytics, settings and all content."},{role:"Admin",scope:"Full site management",details:"Manage all site content, newsletter and non-Super-Admin accounts. Cannot grant, demote or disable Super Admin access."},{role:"Events Manager",scope:"Events only",details:"Create, edit, publish and remove events and full event pages."},{role:"Media Manager",scope:"Gallery only",details:"Manage photos, videos, Drive imports, albums, tags and featured media."},{role:"Team Manager",scope:"Team only",details:"Manage current and past board profiles, bios and board years."},{role:"Viewer",scope:"No CMS editing",details:"Directory-only account. Cannot enter the CMS editor or change site content."}];
const fmt=(v:string|null|undefined)=>v?new Date(v).toLocaleString():"Never";
export default function UsersAccess({actorRole}:{actorRole:"super_admin"|"admin"}){
 const[users,setUsers]=useState<Profile[]>([]),[audit,setAudit]=useState<Audit[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState<Role>("admin"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[resendCooldowns,setResendCooldowns]=useState<Record<string,number>>({}),[now,setNow]=useState(Date.now());const assignable=useMemo(()=>actorRole==="super_admin"?roles:roles.filter(r=>r.value!=="super_admin"),[actorRole]);
 async function load(){const s=createSupabaseBrowserClient();const[{data:u,error:ue},{data:a,error:ae}]=await Promise.all([s.from("profiles").select("id,email,display_name,role,status,created_at,last_seen_at").order("created_at",{ascending:true}),s.from("audit_log").select("id,actor_id,action,created_at,metadata").order("created_at",{ascending:false}).limit(30)]);if(ue||ae)return setMessage(ue?.message||ae?.message||"Unable to load access data.");setUsers((u||[]) as Profile[]);setAudit((a||[]) as Audit[])}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!Object.keys(resendCooldowns).length)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[resendCooldowns]);
 const resendSeconds=(id:string)=>Math.max(0,Math.ceil(((resendCooldowns[id]||0)-now)/1000));
 async function invite(e:FormEvent){e.preventDefault();setLoading(true);setMessage("Sending invitation…");const s=createSupabaseBrowserClient();const{data,error}=await s.functions.invoke("invite-board-member",{body:{email:email.trim(),display_name:name.trim(),role,redirectTo:`${SITE_ORIGIN}/admin/activate`}});setLoading(false);if(error||data?.error)return setMessage(data?.error||error?.message||"Unable to send invitation.");setMessage(`Invitation sent to ${email.trim()}. The activation link opens on nyuperu.org.`);setEmail("");setName("");await load()}
 async function resend(user:Profile){const remaining=resendSeconds(user.id);if(remaining>0)return setMessage(`Please wait ${remaining} seconds before sending another invitation to ${user.email}.`);setLoading(true);setMessage(`Sending a fresh invitation to ${user.email}…`);const s=createSupabaseBrowserClient();const{data,error}=await s.functions.invoke("invite-board-member",{body:{action:"resend",email:user.email,display_name:user.display_name||"",role:user.role,redirectTo:`${SITE_ORIGIN}/admin/activate`}});setLoading(false);if(error||data?.error){const text=String(data?.error||error?.message||"Unable to resend invitation.");if(/rate limit|too many|wait/i.test(text))setResendCooldowns(c=>({...c,[user.id]:Date.now()+RESEND_COOLDOWN_MS}));return setMessage(text)}setResendCooldowns(c=>({...c,[user.id]:Date.now()+RESEND_COOLDOWN_MS}));setNow(Date.now());setMessage(data?.mode==="password_setup"?`Password setup email sent to ${user.email}. It will open the secure setup flow on nyuperu.org.`:`Fresh activation invitation sent to ${user.email}. It will open ${SITE_ORIGIN}/admin/activate.`);await load()}
 async function updateUser(user:Profile,patch:Partial<Pick<Profile,"role"|"status"|"display_name">>){if(actorRole==="admin"&&(user.role==="super_admin"||patch.role==="super_admin"))return setMessage("Only a Super Admin can change Super Admin access.");const s=createSupabaseBrowserClient();const{error}=await s.from("profiles").update(patch).eq("id",user.id);setMessage(error?error.message:"Access updated.");if(!error)await load()}
 const actorName=(id:string|null)=>users.find(u=>u.id===id)?.display_name||users.find(u=>u.id===id)?.email||"System";
 return <main className="access-page"><div className="access-wrap"><div className="access-head"><div><span className="admin-kicker">{actorRole==="super_admin"?"Super Admin":"Admin"}</span><h1>Users & Access</h1><p>Invite board members, assign roles, review activity and control who can change the website.</p></div><a href="/admin" className="admin-primary">← Board CMS</a></div>{message&&<div className="cms-notice">{message}</div>}
 <section className="cms-panel"><span className="admin-kicker">Permissions</span><h2>What each role can do</h2><div className="role-matrix">{permissions.map(x=><article key={x.role}><div><b>{x.role}</b><span>{x.scope}</span></div><p>{x.details}</p></article>)}</div><div className="access-rule"><b>Role-control rule</b><p>Only Super Admins and Admins can change user roles or account status. Admins cannot create, modify, demote or disable a Super Admin.</p></div></section>
 <section className="cms-panel"><span className="admin-kicker">Invite board member</span><h2>Send account invitation</h2><form onSubmit={invite} className="field-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Board member name"/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@nyu.edu"/></label><label>Access role<select value={role} onChange={e=>setRole(e.target.value as Role)}>{assignable.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label><div className="access-submit"><button className="admin-primary" disabled={loading}>{loading?"Sending…":"Send invitation email"}</button></div></form></section>
 <section className="cms-panel"><div className="cms-panel-head"><div><span className="admin-kicker">Authorized accounts</span><h2>Board access</h2></div><b>{users.length} accounts</b></div><div className="access-list">{users.map(user=>{const protect=actorRole==="admin"&&user.role==="super_admin";const cooldown=resendSeconds(user.id);return <article key={user.id} className="access-row"><div><b>{user.display_name||user.email}</b><span>{user.email}</span><small>Invited {new Date(user.created_at).toLocaleDateString()} · Last seen {fmt(user.last_seen_at)}</small></div><label>Role<select value={user.role} disabled={protect} onChange={e=>updateUser(user,{role:e.target.value as Role})}>{roles.map(r=><option key={r.value} value={r.value} disabled={actorRole==="admin"&&r.value==="super_admin"}>{r.label}</option>)}</select></label><label>Status<select value={user.status} disabled={protect} onChange={e=>updateUser(user,{status:e.target.value as Profile["status"]})}><option value="invited">Invited</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label>{user.status==="invited"&&<button onClick={()=>resend(user)} disabled={loading||cooldown>0}>{cooldown>0?`Resend in ${cooldown}s`:"Resend invitation"}</button>}{protect&&<small>Protected Super Admin</small>}</article>})}</div></section>
 <section className="cms-panel"><span className="admin-kicker">Activity log</span><h2>Recent admin actions</h2><div className="activity-list">{audit.map(a=><article key={a.id}><div><b>{a.action.replaceAll("_"," ")}</b><span>{actorName(a.actor_id)}</span></div><time>{fmt(a.created_at)}</time></article>)}</div>{!audit.length&&<p className="empty-state">No admin activity recorded yet.</p>}</section></div></main>;
}
