"use client";

import { useEffect,useState } from "react";

type TrashItem={id:number;entity_type:string;entity_id:string;snapshot:any;deleted_at:string};
type Revision={id:number;snapshot:any;created_at:string};
export default function RecoveryCenter(){
 const[trash,setTrash]=useState<TrashItem[]>([]);const[revisions,setRevisions]=useState<Revision[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/admin/recovery",{cache:"no-store"});const d=await r.json();if(r.ok){setTrash(d.trash||[]);setRevisions(d.revisions||[])}else setMsg(d.error||"Unable to load recovery data.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function restoreTrash(id:number){if(!confirm("Restore this item to the CMS?"))return;const r=await fetch("/api/admin/recovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();setMsg(r.ok?"Item restored.":d.error||"Restore failed.");if(r.ok)void load()}
 async function purge(id:number){if(!confirm("Permanently delete this trash item? This cannot be undone."))return;const r=await fetch(`/api/admin/recovery?id=${id}`,{method:"DELETE"});const d=await r.json();setMsg(r.ok?"Trash item permanently deleted.":d.error||"Delete failed.");if(r.ok)void load()}
 async function restoreRevision(revision:Revision){if(!confirm(`Restore the full CMS to the snapshot from ${new Date(revision.created_at).toLocaleString()}? A new safety revision will be created first.`))return;const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(revision.snapshot)});const d=await r.json();setMsg(r.ok?"CMS restored to the selected revision.":d.error||"Revision restore failed.");if(r.ok)void load()}
 const label=(x:TrashItem)=>x.snapshot?.title||x.snapshot?.name||x.snapshot?.headline||x.entity_id||"Deleted item";
 return <main className="recovery-page"><header><div><a href="/admin">← Admin</a><span className="admin-kicker">Safety & recovery</span><h1>Recovery Center</h1><p>Restore deleted content or roll the CMS back to a previous saved snapshot.</p></div><a className="admin-primary" href="/admin/settings">Settings</a></header>{msg&&<div className="cms-notice">{msg}</div>}{loading?<div className="recovery-loading">Loading recovery data…</div>:<div className="recovery-grid"><section className="recovery-card"><div className="recovery-title"><div><span className="admin-kicker">Trash</span><h2>Recently deleted</h2></div><b>{trash.length}</b></div>{trash.length?trash.map(x=><article className="recovery-row" key={x.id}><div><b>{label(x)}</b><span>{x.entity_type.replaceAll("_"," ")} · {new Date(x.deleted_at).toLocaleString()}</span></div><div><button onClick={()=>restoreTrash(x.id)}>Restore</button><button className="danger" onClick={()=>purge(x.id)}>Delete forever</button></div></article>):<p className="empty-recovery">Trash is empty.</p>}</section><section className="recovery-card"><div className="recovery-title"><div><span className="admin-kicker">Revision history</span><h2>Previous CMS saves</h2></div><b>{revisions.length}</b></div>{revisions.length?revisions.map(x=><article className="recovery-row" key={x.id}><div><b>{new Date(x.created_at).toLocaleString()}</b><span>{x.snapshot?.events?.length||0} events · {x.snapshot?.team?.length||0} team · {x.snapshot?.gallery?.length||0} media</span></div><div><button onClick={()=>restoreRevision(x)}>Restore snapshot</button></div></article>):<p className="empty-recovery">No revisions yet. A snapshot is created before each CMS save.</p>}</section></div>}</main>
}
