"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
import { instagramEmbedUrl, instagramKind, normalizeInstagramUrl } from "../../lib/instagram";

type InstagramPost={id:string;instagram_url:string;caption:string;cover_image:string|null;published:boolean;featured:boolean;sort_order:number;created_at:string};

export default function InstagramAdmin({canEditSettings}:{canEditSettings:boolean}){
  const[posts,setPosts]=useState<InstagramPost[]>([]);const[profileUrl,setProfileUrl]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
  async function load(){const s=createSupabaseBrowserClient();const[{data:p,error},{data:settings}]=await Promise.all([s.from("instagram_posts").select("*").order("sort_order").order("created_at",{ascending:false}),s.from("site_settings").select("instagram").eq("id",1).single()]);if(error)setMessage(error.message);else setPosts((p||[]) as InstagramPost[]);setProfileUrl(settings?.instagram||"");setLoading(false)}
  useEffect(()=>{void load()},[]);
  function add(){setPosts(v=>[{id:`new-${Date.now()}`,instagram_url:"",caption:"",cover_image:null,published:true,featured:false,sort_order:v.length,created_at:new Date().toISOString()},...v])}
  function patch(id:string,p:Partial<InstagramPost>){setPosts(v=>v.map(x=>x.id===id?{...x,...p}:x))}
  async function upload(e:ChangeEvent<HTMLInputElement>,id:string){const file=e.target.files?.[0];if(!file)return;const f=new FormData();f.append("file",file);setMessage("Uploading cover…");const r=await fetch("/api/admin/media",{method:"POST",body:f});const d=await r.json();if(!r.ok)return setMessage(d.error||"Upload failed.");patch(id,{cover_image:d.url});setMessage("Cover uploaded. Save to keep it.")}
  async function save(){setSaving(true);setMessage("Saving Instagram…");const s=createSupabaseBrowserClient();if(canEditSettings){const{error}=await s.from("site_settings").update({instagram:profileUrl.trim()}).eq("id",1);if(error){setSaving(false);return setMessage(error.message)}}const existing=posts.filter(x=>!x.id.startsWith("new-"));const fresh=posts.filter(x=>x.id.startsWith("new-"));for(const p of existing){const url=normalizeInstagramUrl(p.instagram_url);if(!url){setSaving(false);return setMessage(`Invalid Instagram URL: ${p.instagram_url||"blank URL"}`)}const{error}=await s.from("instagram_posts").update({instagram_url:url,caption:p.caption,cover_image:p.cover_image,published:p.published,featured:p.featured,sort_order:p.sort_order}).eq("id",p.id);if(error){setSaving(false);return setMessage(error.message)}}for(const p of fresh){const url=normalizeInstagramUrl(p.instagram_url);if(!url){setSaving(false);return setMessage(`Invalid Instagram URL: ${p.instagram_url||"blank URL"}`)}const{error}=await s.from("instagram_posts").insert({instagram_url:url,caption:p.caption,cover_image:p.cover_image,published:p.published,featured:p.featured,sort_order:p.sort_order});if(error){setSaving(false);return setMessage(error.message)}}setSaving(false);setMessage("Instagram saved. Published posts are now available on the public site.");await load()}
  async function remove(p:InstagramPost){if(!confirm("Remove this Instagram item?"))return;if(p.id.startsWith("new-")){setPosts(v=>v.filter(x=>x.id!==p.id));return}const s=createSupabaseBrowserClient();const{error}=await s.from("instagram_posts").delete().eq("id",p.id);if(error)setMessage(error.message);else{setMessage("Removed.");await load()}}
  if(loading)return <main className="newsletter-admin-page">Loading Instagram manager…</main>;
  return <main className="newsletter-admin-page"><div className="newsletter-admin-wrap"><header className="newsletter-admin-head"><div><span className="admin-kicker">Social media</span><h1>Instagram</h1><p>Paste public Instagram posts or reels, choose what appears on the website, and feature the strongest content.</p></div><div className="campaign-actions"><a className="admin-primary" href="/admin">← Board CMS</a><button className="admin-primary" onClick={save} disabled={saving}>{saving?"Saving…":"Save Instagram"}</button></div></header>{message&&<div className="cms-notice">{message}</div>}
  <section className="cms-panel form-stack"><span className="admin-kicker">Account</span><h2>Instagram profile</h2><label>Profile URL<input value={profileUrl} disabled={!canEditSettings} onChange={e=>setProfileUrl(e.target.value)} placeholder="https://www.instagram.com/perunyu/"/></label>{!canEditSettings&&<small>Admins control the profile URL. Media Managers can manage posts and reels below.</small>}</section>
  <section className="cms-panel"><div className="editor-card-head"><div><span className="admin-kicker">Website feed</span><h2>Posts & reels</h2></div><button className="admin-primary" onClick={add}>＋ Add Instagram item</button></div><p>Paste the normal Instagram share URL. A cover image is optional; when present it gives the site a faster, more controlled visual card while the original post remains linked.</p></section>
  <div className="editor-list">{posts.map((p,i)=>{const embed=instagramEmbedUrl(p.instagram_url);return <article className="cms-panel instagram-editor-card" key={p.id}><div className="instagram-admin-preview">{p.cover_image?<img src={p.cover_image} alt=""/>:embed?<iframe src={embed} title={p.caption||`Instagram ${instagramKind(p.instagram_url)}`} loading="lazy"/>:<div>Paste a post or reel URL to preview it.</div>}</div><div className="form-stack"><div className="editor-card-head"><div><span className="status-pill">{instagramKind(p.instagram_url)}</span><h2>{p.caption||"Instagram item"}</h2></div><button className="danger" onClick={()=>remove(p)}>Delete</button></div><label>Instagram post / reel URL<input value={p.instagram_url} onChange={e=>patch(p.id,{instagram_url:e.target.value})} placeholder="https://www.instagram.com/p/.../"/></label><label>Website caption<textarea value={p.caption} onChange={e=>patch(p.id,{caption:e.target.value})} placeholder="Short context for this post"/></label><div className="field-grid"><label>Order<input type="number" value={p.sort_order} onChange={e=>patch(p.id,{sort_order:Number(e.target.value)})}/></label><label>Visibility<select value={p.published?"published":"hidden"} onChange={e=>patch(p.id,{published:e.target.value==="published"})}><option value="published">Published</option><option value="hidden">Hidden</option></select></label><label>Homepage priority<select value={p.featured?"featured":"normal"} onChange={e=>patch(p.id,{featured:e.target.value==="featured"})}><option value="normal">Normal</option><option value="featured">Featured</option></select></label><label>Cover image URL<input value={p.cover_image||""} onChange={e=>patch(p.id,{cover_image:e.target.value||null})}/></label></div><label className="upload-field">Upload cover image<input type="file" accept="image/*" onChange={e=>upload(e,p.id)}/></label>{p.instagram_url&&<a className="text-link" href={p.instagram_url} target="_blank" rel="noreferrer">Open original on Instagram ↗</a>}</div></article>})}{!posts.length&&<section className="cms-panel"><p>No Instagram posts are managed yet. Add one and paste its Instagram URL.</p></section>}</div></div></main>;
}
