import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "../../../lib/supabase/server";

async function context(){const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{supabase,user:null,profile:null};const{data:profile}=await supabase.from("profiles").select("role,status").eq("id",user.id).single();return{supabase,user,profile}}
const allowed=(p:any)=>p&&p.status==="active"&&["super_admin","admin"].includes(p.role);

export async function GET(){const{supabase,user,profile}=await context();if(!user||!allowed(profile))return NextResponse.json({error:"Unauthorized"},{status:401});const[trash,revisions]=await Promise.all([supabase.from("cms_trash").select("id,entity_type,entity_id,snapshot,deleted_at").order("deleted_at",{ascending:false}).limit(100),supabase.from("cms_revisions").select("id,entity_type,entity_id,snapshot,created_at").order("created_at",{ascending:false}).limit(30)]);if(trash.error||revisions.error)return NextResponse.json({error:(trash.error||revisions.error)?.message},{status:500});return NextResponse.json({trash:trash.data||[],revisions:revisions.data||[]});}

export async function POST(request:Request){const{supabase,user,profile}=await context();if(!user||!allowed(profile))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json();const id=Number(body.id);if(!id)return NextResponse.json({error:"Missing trash item"},{status:400});const{data:item,error}=await supabase.from("cms_trash").select("*").eq("id",id).single();if(error||!item)return NextResponse.json({error:error?.message||"Trash item not found"},{status:404});const table=item.entity_type==="event"?"events":item.entity_type==="team_member"?"team_members":item.entity_type==="gallery_item"?"gallery_items":"";if(!table)return NextResponse.json({error:"Unsupported recovery item"},{status:400});const snapshot={...(item.snapshot||{})};const{error:restoreError}=await supabase.from(table).upsert(snapshot,{onConflict:"id"});if(restoreError)return NextResponse.json({error:restoreError.message},{status:500});await supabase.from("cms_trash").delete().eq("id",id);await supabase.from("audit_log").insert({actor_id:user.id,action:"trash_restore",entity_type:item.entity_type,entity_id:item.entity_id,metadata:{trash_id:id}});return NextResponse.json({ok:true});}

export async function DELETE(request:Request){const{supabase,user,profile}=await context();if(!user||!allowed(profile))return NextResponse.json({error:"Unauthorized"},{status:401});const url=new URL(request.url);const id=Number(url.searchParams.get("id"));if(!id)return NextResponse.json({error:"Missing id"},{status:400});const{error}=await supabase.from("cms_trash").delete().eq("id",id);if(error)return NextResponse.json({error:error.message},{status:500});await supabase.from("audit_log").insert({actor_id:user.id,action:"trash_delete_permanent",entity_type:"cms_trash",entity_id:String(id)});return NextResponse.json({ok:true});}
